import assert from 'node:assert/strict';
import { parseCsv, applyInventoryRows, createBackup, validateBackup } from '../src/domain/backup.js';
import { importDentalRows } from '../src/domain/dental-import.js';
import { takeInventorySnapshot, applyInventorySnapshot } from '../src/domain/inventory-history.js';
import { normalizeProject, fallbackProjectKey, loadProject, listProjects, saveProject } from '../src/data/store.js';
import { createProjectWriter } from '../src/data/persistence.js';
import { ARCHIVE_LIMITS, createOsteoArchive, readOsteoArchive } from '../src/domain/backup-archive.js';
import { normalizePortionRecords, portionRecordCount } from '../src/domain/portion-records.js';
import { normalizeWeightUnit, weightToGrams } from '../src/domain/weights.js';
import { protectSpreadsheetValue, protectSpreadsheetRows } from '../src/domain/spreadsheet.js';
import { downloadModelPackage, removeModelPackage } from '../src/anatomy/package.js';
import { mergeAuxiliaryXlsx } from '../src/ui/extended.js';
import { developmentComponentsForBone, normalizeDevelopmentRecords } from '../src/domain/development.js';
import { calculateNisp, calculateOsteoAnalysis } from '../src/domain/analysis.js';
import { compareHierarchyMetrics, hierarchyInventoryMetrics, hierarchyRecordCounts, hierarchyTree } from '../src/domain/hierarchy.js';

const bones = [{ id: 'skull' }, { id: 'mandible' }, { id: 'left_femur' }];
const xlsxMock = { utils: { sheet_to_json: sheet => sheet.rows || [] } };
const xlsxVisual = mergeAuxiliaryXlsx({}, { Sheets: { 'Configuración visual': { rows: [{ Theta: 1.2, Phi: 0.8, Radius: 9, Target_X: 1, Target_Y: 2, Target_Z: 3 }] } } }, xlsxMock, bones);
assert.deepEqual(xlsxVisual.cameraView, { theta: 1.2, phi: 0.8, radius: 9, target: [1, 2, 3] });
assert.deepEqual(developmentComponentsForBone({ id: 'left_femur' }), ['shaft', 'proximal_epiphysis', 'distal_epiphysis']);
assert.deepEqual(normalizeDevelopmentRecords({ left_femur: { proximal_epiphysis: { status: 'present', fusion: 'partial', completeness: 80, observation: 'visible' }, invalid: { status: 'present' } } }), { left_femur: { proximal_epiphysis: { status: 'present', fusion: 'partial', completeness: 80, observation: 'visible' } } });
const xlsxDevelopment = mergeAuxiliaryXlsx({}, { Sheets: { 'Desarrollo inmaduro': { rows: [{ Bone_ID: 'left_femur', Component_ID: 'shaft', Status: 'fragmentary', Fusion: 'unfused', Completeness: 60, Observation: 'diáfisis conservada' }] } } }, xlsxMock, bones);
assert.equal(xlsxDevelopment.developmentRecords.left_femur.shaft.fusion, 'unfused');
const xlsxHierarchyRefs = mergeAuxiliaryXlsx({}, { Sheets: { 'Asociaciones jerárquicas': { rows: [{ Bone_ID: 'skull', siteId: 'site:norte', contextId: 'context:ue-4', individualId: 'individual:ind-7' }] } } }, xlsxMock, bones);
const xlsxSpecimen = mergeAuxiliaryXlsx({}, { Sheets: { 'Especímenes': { rows: [{ Bone_ID: 'skull', Specimen_ID: 'SP-001' }] } } }, xlsxMock, bones);
assert.equal(xlsxSpecimen.specimens.skull, 'SP-001');
const xlsxSpecimenRecord = mergeAuxiliaryXlsx({}, { Sheets: { 'Fichas de especímenes': { rows: [{ Specimen_ID: 'SP-001', Label: 'Ejemplar', Individual_ID: 'IND-1', Context: 'UE-1', Notes: 'nota' }] } } }, xlsxMock, bones);
assert.deepEqual(xlsxSpecimenRecord.specimenRecords['SP-001'], { id: 'SP-001', label: 'Ejemplar', individualId: 'IND-1', context: 'UE-1', notes: 'nota' });
assert.equal(calculateNisp([{ boneId: 'skull', region: 'Cráneo', side: '—', status: 'present', specimenId: 'SP-001' }, { boneId: 'skull', region: 'Cráneo', side: '—', status: 'fragmentary', specimenId: 'SP-001' }]).value, 1);
assert.deepEqual(validateBackup(createBackup({ specimens: { skull: 'SP-001' } })).specimens, { skull: 'SP-001' });
const specimenAnalysis = calculateOsteoAnalysis(bones, { status: { skull: 'present' }, specimens: { skull: 'SP-001' } });
assert.deepEqual(specimenAnalysis.specimenCoverage, { identified: 1, withSpecimenId: 1, withoutSpecimenId: 0, uniqueSpecimenIds: 1, conflicts: [] });
const specimenConflict = calculateOsteoAnalysis(bones, { status: { skull: 'present', mandible: 'present' }, specimens: { skull: 'SP-001', mandible: 'SP-001' }, individuals: { skull: 'IND-1', mandible: 'IND-2' } });
assert.deepEqual(specimenConflict.specimenCoverage.conflicts, [{ specimenId: 'SP-001', individuals: ['IND-1', 'IND-2'], contexts: [] }]);
assert.equal(calculateOsteoAnalysis(bones, { status: { skull: 'present', mandible: 'present' }, individuals: { skull: 'IND-1', mandible: 'IND-2' } }).mni.value, 1, 'MNI must use the maximum duplicate element-side group, not global individual count');
const specimenFallback = calculateOsteoAnalysis(bones, { status: { skull: 'present' }, specimens: { skull: 'SP-002' }, specimenRecords: { 'SP-002': { id: 'SP-002', individualId: 'IND-2', context: 'UE-2' } } });
assert.equal(specimenFallback.rows[0].individual, 'IND-2');
assert.equal(specimenFallback.rows[0].context, 'UE-2');
assert.deepEqual(xlsxHierarchyRefs.hierarchyRefs.skull, { siteId: 'site:norte', contextId: 'context:ue-4', individualId: 'individual:ind-7' });
const previousCaches = globalThis.caches;
const previousFetch = globalThis.fetch;
const packageEntries = new Map([['./models/test/a.glb', new Response('old')]]);
globalThis.caches = { open: async () => ({ match: async url => packageEntries.get(url) || undefined, put: async (url, response) => packageEntries.set(url, response), delete: async url => packageEntries.delete(url) }) };
globalThis.fetch = async url => url.endsWith('/b.glb') ? new Response('', { status: 503 }) : new Response('new');
await assert.rejects(() => downloadModelPackage({ schema_version: 1, bone_asset_pattern: '{profile}/{bone_id}.glb', required_metadata: ['license'], profiles: { test: { root: 'test', asset_status: 'ready', asset_ids: ['a', 'b'] } } }, 'test', [{ id: 'a' }, { id: 'b' }]), /No se pudo descargar/);
assert.equal(await (await globalThis.caches.open()).match('./models/test/a.glb').then(response => response.text()), 'old');
assert.equal(packageEntries.has('./models/test/b.glb'), false);
packageEntries.set('./models/custom/test/skull.glb', new Response('custom'));
await removeModelPackage({ schema_version: 1, bone_asset_pattern: '{profile}/{bone_id}.glb', required_metadata: ['license'], profiles: { test: { root: 'test', asset_status: 'ready', asset_ids: ['a', 'b'] } } }, 'test', [{ id: 'a' }, { id: 'b' }]);
assert.equal(packageEntries.has('./models/custom/test/skull.glb'), true);
globalThis.caches = previousCaches;
globalThis.fetch = previousFetch;
assert.equal(protectSpreadsheetValue('=SUM(A1:A2)'), "'=SUM(A1:A2)");
assert.equal(protectSpreadsheetValue('+cmd'), "'+cmd");
assert.equal(protectSpreadsheetValue('-10'), "'-10");
assert.equal(protectSpreadsheetValue('texto normal'), 'texto normal');
assert.deepEqual(protectSpreadsheetRows([{ Notes: '@usuario', Fragments: 0 }]), [{ Notes: "'@usuario", Fragments: 0 }]);
const archiveBytes = await createOsteoArchive(createBackup({ projectId: 'archive-1', projectName: 'Copia con GLB' }), [{ name: 'models/custom/infant/left_femur.glb', data: new Uint8Array([0, 1, 2, 255]) }]);
const archive = await readOsteoArchive(archiveBytes);
assert.equal(archive.project.project.projectName, 'Copia con GLB');
assert.equal(archive.models[0].name, 'models/custom/infant/left_femur.glb');
assert.deepEqual([...archive.models[0].data], [0, 1, 2, 255]);
assert.match(archive.manifest.checksums[archive.models[0].name], /^[0-9a-f]{8}$/);
assert.match(archive.manifest.sha256['project.json'], /^[0-9a-f]{64}$/);
assert.match(archive.manifest.sha256[archive.models[0].name], /^[0-9a-f]{64}$/);
await assert.rejects(() => readOsteoArchive(new Uint8Array([1, 2, 3])));
const oversizedHeader = new Uint8Array(34); oversizedHeader.set([0x50, 0x4b, 0x03, 0x04]); new DataView(oversizedHeader.buffer).setUint32(18, ARCHIVE_LIMITS.maxEntryBytes + 1, true); new DataView(oversizedHeader.buffer).setUint32(22, ARCHIVE_LIMITS.maxEntryBytes + 1, true); await assert.rejects(() => readOsteoArchive(oversizedHeader), /demasiado grande|inseguro/i);
const corruptedArchive = new Uint8Array(archiveBytes); corruptedArchive[corruptedArchive.indexOf(255)] = 254;
await assert.rejects(() => readOsteoArchive(corruptedArchive), /dañado|damaged/i);
const csv = '\uFEFFBone_ID,Notes,Weight_g\r\nskull,"línea 1, \"\"comillas\"\"\r\nlínea 2",0\r\n\r\nmandible,"",\r\n';
const rows = parseCsv(csv);
assert.equal(rows.length, 2);
assert.equal(rows[0].Notes, 'línea 1, "comillas"\r\nlínea 2');
assert.equal(rows[0].Weight_g, '0');
assert.equal(rows[1].Notes, '');
for (const invalid of ['Bone_ID,Notes\nskull,"sin cierre', 'Bone_ID,Notes\nskull,"a"b', 'Bone_ID,Notes\nskull,a"b', 'Bone_ID,Notes\nskull', 'Bone_ID,Notes\nskull,a,extra', 'Bone_ID,Bone_ID\nskull,a']) assert.throws(() => parseCsv(invalid));
const original = { status: { skull: 'present' }, completeness: { skull: 40 }, fragments: { skull: 3 }, weights: { skull: 12 }, notes: { skull: 'original' }, report: { site: 'Original' } };
const untouched = structuredClone(original);
const partial = applyInventoryRows(original, [{ Bone_ID: 'skull', Weight_g: '', Presence: '', Notes: 'nota nueva' }], bones);
assert.equal(partial.status.skull, 'present');
assert.equal(partial.completeness.skull, 40);
assert.equal(partial.weights.skull, 12);
assert.equal(partial.fragments.skull, 3);
assert.equal(partial.notes.skull, 'nota nueva');
assert.deepEqual(original, untouched, 'Import is pure until confirmed');
const unknown = applyInventoryRows({}, [{ Bone_ID: 'skull', Weight_g: '', Fragments: null, Completeness: ' ' }], bones);
assert.deepEqual(unknown.weights, {});
assert.deepEqual(unknown.fragments, {});
assert.deepEqual(unknown.completeness, {});
const zero = applyInventoryRows({}, [{ Bone_ID: 'skull', Weight_g: 0, Fragments: '0', Completeness: 0, Presence: ' present ' }], bones);
assert.equal(zero.weights.skull, 0);
assert.equal(zero.fragments.skull, 0);
assert.equal(zero.completeness.skull, 0);
assert.equal(zero.status.skull, 'present');
const rejected = applyInventoryRows({ ...original, locked: { skull: true } }, [{ Bone_ID: 'skull', Notes: 'no', Site: 'Rejected' }, { Bone_ID: 'mandible', Weight_g: -1, Site: 'Rejected' }, { Bone_ID: 'left_femur', Presence: 'present', Taphonomy_Detail: '{bad' }], bones);
assert.equal(rejected.rejectedRows, 3);
assert.equal(rejected.importedRows, 0);
assert.equal(rejected.notes.skull, 'original');
assert.equal(rejected.status.left_femur, undefined, 'A malformed field rejects its entire row');
assert.equal(rejected.report.site, 'Original');
const duplicates = applyInventoryRows({}, [{ Bone_ID: 'skull', Weight_g: '-1' }, { Bone_ID: 'skull', Weight_g: '3' }], bones);
assert.equal(duplicates.rejectedRows, 2, 'Duplicate ID rejected even after an invalid first row');
for (const value of [null, undefined, '', ' ', false, [], {}]) {
  const project = normalizeProject({ weights: { skull: value }, fragments: { skull: value }, completeness: { skull: value } });
  assert.deepEqual(project.weights, {}); assert.deepEqual(project.fragments, {}); assert.deepEqual(project.completeness, {});
}
assert.equal(normalizeProject({ weights: { skull: 0 } }).weights.skull, 0);
assert.equal(normalizeProject([]), null);
assert.throws(() => validateBackup({ format: 'osteo3d-project-backup', version: 1, project: [] }));
const visualBackup = validateBackup(createBackup({ skeletonFilter: 'axial', regionFilter: 'Cráneo', explosion: 70, tableMode: true, orthographic: true, isolate: true, lightingMode: 'laboratory' }));
assert.equal(visualBackup.explosion, 70); assert.equal(visualBackup.tableMode, true); assert.equal(visualBackup.lightingMode, 'laboratory');
const cameraView = { theta: 1.2, phi: 0.8, radius: 9, target: [1, 2, 3] };
assert.deepEqual(validateBackup(createBackup({ cameraView })).cameraView, cameraView);
assert.deepEqual(normalizeProject({ cameraView: { theta: 2, phi: 99, radius: 999, target: [1, 2, 3] } }).cameraView, { theta: 2, phi: Math.PI - 0.12, radius: 40, target: [1, 2, 3] });
const calibrationBackup = validateBackup(createBackup({ calibrations: { skull: { referenceMm: 50, localDistance: 2 } } }));
assert.deepEqual(calibrationBackup.calibrations.skull, { referenceMm: 50, localDistance: 2 });
const hierarchyRefs = { skull: { siteId: 'site:norte', campaignId: 'campaign:2026', contextId: 'context:ue-4', invalid: 'ignored-by-normalizer' } };
const hierarchyForRefs = { sites: [{ id: 'site:norte', name: 'Norte' }], campaigns: [{ id: 'campaign:2026', name: '2026', parentId: 'site:norte' }], sectors: [], contexts: [{ id: 'context:ue-4', name: 'UE-4' }], individuals: [] };
assert.deepEqual(validateBackup(createBackup({ hierarchyRefs, hierarchy: hierarchyForRefs })).hierarchyRefs, { skull: { siteId: 'site:norte', campaignId: 'campaign:2026', contextId: 'context:ue-4' } });
assert.deepEqual(normalizeProject({ hierarchy: hierarchyForRefs, hierarchyRefs: { skull: { siteId: 'site:missing', contextId: 'campaign:2026', contextId2: 'bad' } } }).hierarchyRefs, {});
const modelReference = { skull: { profile: 'adult_male', source: 'custom', geometryVersion: 'external', customUpdatedAt: '2026-09-09T12:00:00Z', needsReview: true } };
const modelReferenceBackup = validateBackup(createBackup({ landmarkModelRefs: modelReference }));
assert.deepEqual(modelReferenceBackup.landmarkModelRefs, modelReference);
const portions = normalizePortionRecords({ left_femur: { epiphysis_proximal: { status: 'present', completeness: 80 }, shaft_mid: { status: 'fragmentary', fragments: 2 }, invalid: { status: 'bad' } } });
assert.equal(portions.left_femur.epiphysis_proximal.completeness, 80);
assert.equal(portions.left_femur.shaft_mid.fragments, 2);
assert.equal(portionRecordCount(portions), 2);
assert.deepEqual(normalizeProject({ portionRecords: portions }).portionRecords, portions);
assert.equal(normalizeWeightUnit('KG'), 'kg');
assert.equal(weightToGrams(1.25, 'kg'), 1250);
assert.equal(weightToGrams(0, 'g'), 0);
assert.equal(weightToGrams('', 'kg'), null);
assert.equal(normalizeProject({ weights: { skull: 1.25 }, weightUnits: { skull: 'kg' } }).weightUnits.skull, 'kg');
assert.equal(validateBackup(createBackup({ weights: { skull: 0 }, notes: { skull: rows[0].Notes } })).notes.skull, rows[0].Notes);

assert.deepEqual(importDentalRows({ 12: 'caries' }, [{ Tooth_FDI: 11, Status: 'Presente' }, { Tooth_FDI: 12, Status: '' }]), { 11: 'present', 12: 'caries' });
assert.deepEqual(importDentalRows({ 51: 'present' }, [{ Tooth_FDI: 51, Status: 'not_recorded' }], { deciduous: true }), {});
assert.deepEqual(importDentalRows({ 11: 'present' }, [{ Tooth_FDI: 11, Status: 'absent_pm' }], { locked: { 11: true } }), { 11: 'present' });
assert.throws(() => importDentalRows({}, [{ Tooth_FDI: 51, Status: 'present' }]));
assert.throws(() => importDentalRows({}, [{ Tooth_FDI: 11, Status: 'unexpected' }]));
assert.throws(() => importDentalRows({}, [{ Tooth_FDI: 11, Status: 'present' }, { Tooth_FDI: 11, Status: 'wear' }]));
const state = { ...original, hierarchyRefs: { skull: { contextId: 'context:ue-4' } }, pathologyDetails: { skull: { description: 'antes' } }, dental: { 11: 'wear' }, developmentRecords: { left_femur: { shaft: { status: 'present', fusion: 'unfused' } } }, skeletonFilter: 'axial', regionFilter: 'Cráneo' };
const snapshot = takeInventorySnapshot(state);
state.weights.skull = 99; state.pathologyDetails.skull.description = 'después'; state.dental[11] = 'caries'; state.developmentRecords.left_femur.shaft.fusion = 'fused'; state.skeletonFilter = 'appendicular'; state.regionFilter = 'Pelvis';
applyInventorySnapshot(state, snapshot);
assert.equal(state.weights.skull, 12); assert.equal(state.pathologyDetails.skull.description, 'antes'); assert.equal(state.dental[11], 'wear'); assert.equal(state.developmentRecords.left_femur.shaft.fusion, 'unfused'); assert.equal(state.skeletonFilter, 'axial'); assert.equal(state.regionFilter, 'Cráneo');
assert.equal(state.hierarchyRefs.skull.contextId, 'context:ue-4');
const hierarchyAnalysis = calculateOsteoAnalysis(bones, { status: { skull: 'present' }, hierarchyRefs: { skull: { contextId: 'context:ue-4', individualId: 'individual:ind-7' } }, hierarchy: { contexts: [{ id: 'context:ue-4', name: 'UE-4' }], individuals: [{ id: 'individual:ind-7', name: 'IND-7' }] } });
assert.equal(hierarchyAnalysis.rows[0].context, 'UE-4');
assert.equal(hierarchyAnalysis.rows[0].individual, 'IND-7');
const relationalTree = hierarchyTree(hierarchyForRefs);
assert.equal(relationalTree[0].children[0].name, '2026');
assert.equal(relationalTree[0].children[0].children.length, 0, 'Relational hierarchy keeps empty intermediate levels visible');
assert.deepEqual(hierarchyRecordCounts(hierarchyForRefs, { skull: { siteId: 'site:norte', campaignId: 'campaign:2026', contextId: 'context:ue-4' } }), { sites: { 'site:norte': 1 }, campaigns: { 'campaign:2026': 1 }, sectors: {}, contexts: { 'context:ue-4': 1 }, individuals: {} });
assert.deepEqual(hierarchyInventoryMetrics(hierarchyForRefs, { skull: { siteId: 'site:norte', campaignId: 'campaign:2026', contextId: 'context:ue-4' } }, { skull: 'present' }).campaigns['campaign:2026'], { records: 1, reviewed: 1, present: 1 });
assert.deepEqual(compareHierarchyMetrics({ campaigns: { 'campaign:2026': { records: 1, reviewed: 1, present: 1 }, 'campaign:2027': { records: 3, reviewed: 2, present: 1 } } }, 'campaigns', 'campaign:2026'), [{ id: 'campaign:2026', recordsDelta: 0, reviewedDelta: 0, presentDelta: 0 }, { id: 'campaign:2027', recordsDelta: 2, reviewedDelta: 1, presentDelta: 0 }]);
const staleAnalysis = calculateOsteoAnalysis(bones, { status: { skull: 'present' }, analysisReview: { nisp: { value: 99, reason: 'revisión anterior', signature: 'old' } } });
assert.equal(staleAnalysis.nisp.reviewStatus, 'stale');
state.pathologyDetails.skull.description = 'nueva';
assert.equal(snapshot.pathologyDetails.skull.description, 'antes', 'Undo snapshots cannot be mutated by later edits');
const modelReferenceState = { landmarkModelRefs: modelReference };
const modelReferenceSnapshot = takeInventorySnapshot(modelReferenceState);
modelReferenceState.landmarkModelRefs.skull.needsReview = false;
applyInventorySnapshot(modelReferenceState, modelReferenceSnapshot);
assert.equal(modelReferenceState.landmarkModelRefs.skull.needsReview, true, 'Model review flags are undoable');
const photoState = { photos: { skull: [{ name: 'a', dataUrl: 'data:image/png;base64,AA' }] }, indeterminateFragments: [{ type: 'astilla' }] };
const photoSnapshot = takeInventorySnapshot(photoState);
photoState.photos.skull.push({ name: 'b', dataUrl: 'data:image/png;base64,BB' }); photoState.indeterminateFragments.splice(0, 1);
applyInventorySnapshot(photoState, photoSnapshot);
assert.equal(photoState.photos.skull.length, 1, 'Photo additions are undoable as part of the common snapshot');
assert.equal(photoState.indeterminateFragments.length, 1, 'Indeterminate-fragment changes are undoable as part of the common snapshot');
assert.ok(takeInventorySnapshot(photoState).photos.skull[0].dataUrl.startsWith('data:image/'), 'Photo data remains in the undo snapshot');

class MemoryStorage {
  values = new Map();
  get length() { return this.values.size; }
  key(index) { return [...this.values.keys()][index] ?? null; }
  getItem(key) { return this.values.get(key) ?? null; }
  setItem(key, value) { this.values.set(key, String(value)); }
  removeItem(key) { this.values.delete(key); }
}
const storage = new MemoryStorage(), fail = async () => { throw new Error('IDB unavailable'); };
const fallbackWriter = createProjectWriter({ primary: fail, storage: () => storage });
assert.equal((await fallbackWriter({ id: 'A', weights: { skull: 2 }, updatedAt: '2026-09-09T12:00:00Z' })).backend, 'localStorage');
assert.equal((await fallbackWriter({ id: 'B', weights: { skull: 3 } })).ok, true);
assert.equal(JSON.parse(storage.getItem(fallbackProjectKey('A'))).weights.skull, 2);
assert.equal(JSON.parse(storage.getItem(fallbackProjectKey('B'))).weights.skull, 3);
const failedWriter = createProjectWriter({ primary: fail, storage: () => ({ setItem() { throw new Error('Quota'); } }) });
assert.equal((await failedWriter({ id: 'A' })).ok, false);
const primaryWriter = createProjectWriter({ primary: async () => {}, storage: () => storage });
assert.equal((await primaryWriter({ id: 'A' })).backend, 'indexedDB');
assert.equal(storage.getItem(fallbackProjectKey('A')), null, 'Successful primary save clears superseded fallback');
const written = []; let release;
const queued = createProjectWriter({ primary: async project => { written.push(project); if (written.length === 1) await new Promise(resolve => { release = resolve; }); }, storage: () => storage });
const draft = { id: 'A', weights: { skull: 4 } };
const firstSave = queued(draft);
draft.weights.skull = 5;
const secondSave = queued(draft);
await Promise.resolve(); assert.equal(written.length, 1); release(); await Promise.all([firstSave, secondSave]);
assert.deepEqual(written.map(project => project.weights.skull), [4, 5]);

globalThis.localStorage = storage;
globalThis.window = {};
storage.setItem('osteo3d-mvp', JSON.stringify({ id: 'legacy', weights: { skull: 9 } }));
assert.equal((await loadProject('B')).weights.skull, 3);
assert.equal((await loadProject('legacy')).weights.skull, 9);
assert.equal(await loadProject('missing'), null, 'Never load a different project when an ID is missing');
assert.deepEqual((await listProjects()).map(project => project.id).sort(), ['B', 'legacy']);
let closed = false;
const db = {
  transaction() {
    const tx = { objectStore() { return { put() { queueMicrotask(() => tx.onabort()); } }; } };
    return tx;
  }, close() { closed = true; }
};
globalThis.window.indexedDB = globalThis.indexedDB = { open() { const request = { result: db }; queueMicrotask(() => request.onsuccess()); return request; } };
await assert.rejects(saveProject({ id: 'A' }), /cancelada/);
assert.equal(closed, true, 'Aborted transactions close their database connection');
let lateClose = false;
globalThis.indexedDB = { open() { const request = { result: { close() { lateClose = true; } } }; queueMicrotask(() => { request.onblocked(); queueMicrotask(() => request.onsuccess()); }); return request; } };
await assert.rejects(saveProject({ id: 'A' }), /bloqueado/);
await Promise.resolve(); assert.equal(lateClose, true, 'A late database connection is closed after a blocked-open failure');
storage.setItem(fallbackProjectKey('A'), JSON.stringify({ id: 'A', weights: { skull: 7 }, updatedAt: '2026-09-09T12:00:00Z' }));
const older = { id: 'A', weights: { skull: 1 }, updatedAt: '2026-09-08T12:00:00Z' };
globalThis.indexedDB = { open() {
  const request = { result: { close() {}, transaction() { return { objectStore() {
    const result = value => { const get = { result: value }; queueMicrotask(() => get.onsuccess()); return get; };
    return { get: () => result(older), getAll: () => result([older]) };
  } }; } } }; queueMicrotask(() => request.onsuccess()); return request;
} };
assert.equal((await loadProject('A')).weights.skull, 7, 'Latest fallback supersedes a stale IndexedDB record');
assert.equal((await listProjects()).find(project => project.id === 'A').weights.skull, 7);
console.log('Data integrity: CSV multiline/strict parsing, blank vs zero, locks, atomic rows, dental codes, undo, queued saves and storage failures OK');
