import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { access } from 'node:fs/promises';
import { calculateOsteoAnalysis } from '../src/domain/analysis.js';
import { portionOptionsForBone } from '../src/domain/portions.js';
import { downloadModelPackage, formatPackageSize, modelPackageDownloadPlan, modelPackageSummary, validateModelManifest, validateModelSourceRegistry } from '../src/anatomy/package.js';
import { applyInventoryRows, createBackup, parseCsv, validateBackup } from '../src/domain/backup.js';

const text = async path => readFile(path, 'utf8');
const exists = async path => { try { await access(path); return true; } catch { return false; } };

const manifest = JSON.parse(await text('public/manifest.json'));
assert.equal(manifest.display, 'standalone');
assert.equal(manifest.start_url, './');
assert.ok(manifest.icons.length > 0);
assert.equal(manifest.icons.length, 4);
assert.equal(manifest.icons[0].type, 'image/png');
assert.equal(manifest.icons[1].type, 'image/png');
assert.equal(manifest.icons[0].sizes, '192x192');
assert.equal(manifest.icons[1].sizes, '512x512');
assert.equal(manifest.shortcuts.length, 2);
assert.equal(manifest.shortcuts[0].url, './?view=inventory');
assert.equal(manifest.shortcuts[1].url, './?view=report');

const sw = await text('public/sw.js');
assert.match(sw, /caches\.open/);
assert.match(sw, /SKIP_WAITING/);
assert.match(sw, /cache: 'reload'/);
assert.match(sw, /no-store/);
assert.match(sw, /assetPathsFromHtml/);
assert.match(sw, /assets/);
assert.match(sw, /osteo3d-shell-v7/);
assert.match(sw, /osteo3d-192\.png/);
assert.match(sw, /osteo3d-512\.png/);
assert.match(sw, /models\/manifest\.json/);
assert.match(sw, /models\/sources\.json/);
assert.match(sw, /osteo3d-192\.svg/);
assert.match(sw, /osteo3d-512\.svg/);
assert.match(sw, /startsWith\('osteo3d-shell-'\)/);
assert.match(sw, /caches\.delete/);

const main = await text('src/main.js');
const store = await text('src/data/store.js');
assert.match(store, /indexedDB/);
assert.match(store, /PROJECT_SCHEMA_VERSION = 2/);
assert.match(store, /normalizeProject/);
assert.match(store, /localStorage\.getItem/);
assert.match(store, /listProjects/);
assert.match(store, /projectName/);
assert.match(main, /setInterval\(\(\) =>/);
assert.match(main, /connection-status/);
assert.match(main, /filter-taphonomy/);
assert.match(main, /filter-pathology/);
assert.match(main, /deciduousTeeth/);
assert.match(main, /dentition-type/);
assert.match(main, /Odontograma deciduo/);
assert.equal(manifest.scope, './');
for (const marker of ['PINTAR INVENTARIO', 'ODONTOGRAMA', 'OSTEOMETRÍA', 'ESTADÍSTICAS', 'INFORME OSTEOARQUEOLÓGICO', 'exportXlsx', 'registerPwa']) {
  assert.match(main, new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `Falta módulo: ${marker}`);
}
assert.match(main, /project-selector/);
assert.match(main, /new-project/);
assert.match(main, /verifyModelPackages/);
assert.match(main, /protectLocalStorage/);
assert.match(main, /navigator\.storage\.persist/);
assert.match(main, /storage-status/);
assert.match(main, /pwa-diagnostics/);
assert.match(main, /runPwaDiagnostics/);
assert.match(main, /beforeinstallprompt/);
assert.match(main, /appinstalled/);
assert.match(main, /disponible en este navegador/);
assert.match(main, /osteo3d-shell-v7/);
assert.match(main, /Iconos PWA/);
assert.match(main, /HTML, datos e iconos en caché/);
assert.match(main, /models\/sources\.json/);
assert.match(main, /applyPwaLaunchView/);
assert.match(main, /inventory-progress-label/);
assert.match(main, /Presencia rápida/);
assert.match(main, /Marcar restantes como ausentes/);
assert.match(main, /window\.confirm\(`Se marcarán/);
assert.match(main, /status-legend/);
assert.match(main, /Inventario completado/);
assert.match(main, /recordInventoryChange/);
assert.match(main, /recordInventorySnapshotChanges/);
assert.match(main, /mass_absent/);
assert.match(main, /mass_region/);
assert.match(main, /recordInventorySnapshotChanges\(current,previous,'undo'\)/);
assert.match(main, /changeLog/);
assert.match(main, /locked:state\.locked,changeLog:state\.changeLog/);
assert.match(main, /changeLog: \[\], quickPresent: false/);
assert.match(main, /changeLog:state\.changeLog},null,2/);
assert.match(await text('src/ui/extended.js'), /Registro de cambios/);
assert.match(await text('src/ui/extended.js'), /changedAt/);
assert.match(main, /model-package-panel/);
assert.match(main, /downloadSelectedModelPackage/);
assert.match(main, /Pendiente de incorporar assets licenciados/);
assert.match(main, /Descargar paquete offline/);
assert.match(main, /loadBoneModel/);
assert.match(main, /loadAvailableProfileModels/);
assert.match(main, /modelSource: 'glb'/);
assert.match(main, /intersectObjects\(group\.children, true\)/);
assert.match(main, /listProjects, loadProject/);
assert.match(await text('src/ui/extended.js'), /compare-project/);
assert.match(await text('src/ui/extended.js'), /diferencias frente a/);
assert.match(main, /Actualizar ahora/);
assert.match(main, /Más tarde/);
assert.match(main, /await saveLocal\(\{ notify:false \}\)/);
assert.match(main, /if\(updateRequested\) window\.location\.reload/);
assert.match(main, /onWheel/);
assert.match(main, /onPointerMove/);
assert.match(main, /orbit\.target/);
assert.match(main, /tabIndex = 0/);
assert.match(main, /aria-label.*Visor 3D/);
assert.match(main, /onViewerKeyDown/);
assert.match(main, /ArrowLeft/);
assert.match(main, /toLowerCase\(\) === 'r'/);
assert.match(main, /activePointers/);
assert.match(main, /pinchDistance/);
assert.match(main, /pointerDistance/);

assert.equal(await exists('src/anatomy/catalog.js'), true);
assert.equal(await exists('src/anatomy/loader.js'), true);
assert.equal(await exists('src/anatomy/extended-bones.js'), true);
const { extendedBones } = await import('../src/anatomy/extended-bones.js');
assert.ok(extendedBones.length > 100, 'expanded catalog should contain independent placeholders');
assert.ok(extendedBones.some((bone) => bone.id === 'left_rib_1'));
assert.equal(await exists('public/models/manifest.json'), true);
assert.equal(await exists('public/icons/osteo3d-192.svg'), true);
assert.equal(await exists('public/icons/osteo3d-512.svg'), true);
assert.equal(await exists('public/icons/osteo3d-192.png'), true);
assert.equal(await exists('public/icons/osteo3d-512.png'), true);
const modelManifest = JSON.parse(await text('public/models/manifest.json'));
assert.equal(validateModelManifest(modelManifest, extendedBones).valid, true);
assert.equal(modelManifest.bone_count, 178);
assert.equal(modelPackageSummary(modelManifest, 'infant', extendedBones).status, 'placeholder');
assert.equal(formatPackageSize(null), 'no disponible');
assert.equal(formatPackageSize(42.5), 'aprox. 42.5 MB');
const sourceRegistry = JSON.parse(await text('public/models/sources.json'));
assert.equal(validateModelSourceRegistry(modelManifest, sourceRegistry).valid, true);
assert.equal(validateModelSourceRegistry({ profiles: { adult_male: { asset_status: 'ready' } } }, sourceRegistry).valid, false);
assert.equal(validateModelSourceRegistry(modelManifest, { ...sourceRegistry, schema_version: 99 }).valid, false);
assert.equal(validateModelSourceRegistry(modelManifest, { schema_version: 1, profiles: { adult_male: { source_status: 'pending' } } }).valid, false);
assert.match(await text('src/anatomy/loader.js'), /loadModelSourceRegistry/);
assert.equal(await exists('public/models/SOURCES.md'), true);
assert.equal(await exists('scripts/validate-model-assets.mjs'), true);
const packagePlan = modelPackageDownloadPlan(modelManifest, 'adult_male', [{ id: 'skull' }].map(bone => bone.id));
assert.equal(packagePlan.urls[0], './models/adult_male/skull.glb');
await assert.rejects(() => downloadModelPackage(modelManifest, 'adult_male', ['skull']), /placeholder/);
assert.equal(await exists('dist/index.html'), true);
assert.equal(await exists('dist/sw.js'), true);
assert.equal(await exists('src/domain/analysis.js'), true);
assert.equal(await exists('src/domain/backup.js'), true);
assert.equal(await exists('src/ui/extended.js'), true);

const testBones = [
  { id: 'left_femur', es: 'Fémur izquierdo', region: 'Extremidad inferior', side: 'Izquierda' },
  { id: 'right_femur', es: 'Fémur derecho', region: 'Extremidad inferior', side: 'Derecha' }
];
const testState = { status: { left_femur: 'fragmentary', right_femur: 'not_recorded' }, fragments: { left_femur: 2 }, portions: { left_femur: 'epiphysis_proximal' }, individuals: { left_femur: 'IND-A' }, report: { individual: 'IND-TEST' } };
const analysis = calculateOsteoAnalysis(testBones, testState);
assert.equal(analysis.nisp.value, 1);
assert.equal(analysis.mne.value, 2);
assert.equal(analysis.mni.value, 2);
assert.equal(analysis.individuals.value, 1);
assert.equal(analysis.individuals.rows[0].individual, 'IND-A');
assert.ok(portionOptionsForBone({ type: 'long_bone' }).some(([key]) => key === 'epiphysis_proximal'));
assert.ok(!portionOptionsForBone({ type: 'rib' }).some(([key]) => key === 'epiphysis_proximal'));
assert.equal(parseCsv('Bone_ID,Presence\nleft_femur,present')[0].Bone_ID, 'left_femur');
const imported = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Presence: 'present', Individual_ID: 'IND-B', Portion: 'shaft_mid', Taphonomy: 'raíces; erosión', Pathology: 'fractura' }], testBones);
assert.equal(imported.status.left_femur, 'present');
assert.equal(imported.individuals.left_femur, 'IND-B');
assert.equal(imported.portions.left_femur, 'shaft_mid');
assert.deepEqual(imported.taphonomy.left_femur, ['raíces', 'erosión']);
assert.throws(() => validateBackup({ format: 'wrong' }));
const backup = createBackup({ profile: 'infant', status: {}, preservation: {}, completeness: {}, fragments: {}, portions: {}, individuals: {}, taphonomy: {}, pathology: {}, notes: {}, locked: {}, dental: {}, deciduousDental: { '51': 'present' }, dentitionType: 'deciduous', measurements: {}, landmarks: {}, photos: {}, report: {} });
assert.equal(validateBackup(backup).deciduousDental['51'], 'present');
assert.deepEqual(validateBackup(createBackup({ ...backup.project, changeLog: [{ boneId: 'skull', previousStatus: 'not_recorded', newStatus: 'present' }] })).changeLog[0].newStatus, 'present');

console.log('Osteo3D smoke tests: OK');
