import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { access } from 'node:fs/promises';
import { calculateOsteoAnalysis } from '../src/domain/analysis.js';
import { portionOptionsForBone } from '../src/domain/portions.js';
import { cacheCustomModelFile, customModelUrl, downloadModelPackage, formatPackageSize, getCachedModelBoneIds, glbContainsBoneId, importModelPackageFiles, modelPackageDownloadPlan, modelPackageSummary, validateModelManifest, validateModelSourceRegistry } from '../src/anatomy/package.js';
import { applyInventoryRows, createBackup, parseCsv, validateBackup } from '../src/domain/backup.js';
import { normalizeProject } from '../src/data/store.js';
import { mergeAuxiliaryXlsx } from '../src/ui/extended.js';

const text = async path => readFile(path, 'utf8');
const exists = async path => { try { await access(path); return true; } catch { return false; } };

const manifest = JSON.parse(await text('public/manifest.json'));
const packageJson = JSON.parse(await text('package.json'));
const indexHtml = await text('index.html');
assert.equal(await exists('PWA_STATUS.md'), true);
assert.match(await text('PWA_STATUS.md'), /Estado operativo verificado/);
assert.match(await text('PWA_STATUS.md'), /placeholder/);
assert.match(indexHtml, /apple-mobile-web-app-capable/);
assert.match(indexHtml, /apple-touch-icon.*osteo3d-192\.png/);
assert.equal(manifest.display, 'standalone');
assert.equal(packageJson.version, '1.0.0');
assert.equal(manifest.id, './');
assert.equal(manifest.lang, 'es');
assert.equal(manifest.dir, 'ltr');
assert.equal(manifest.orientation, 'any');
assert.equal(manifest.theme_color, '#102a43');
assert.equal(manifest.background_color, '#f5f7fa');
assert.equal(manifest.prefer_related_applications, false);
assert.ok(manifest.display_override.includes('standalone'));
assert.ok(manifest.description.length > 0);
assert.equal(manifest.start_url, './');
assert.ok(manifest.icons.length > 0);
assert.equal(manifest.icons.length, 4);
assert.equal(manifest.icons[0].type, 'image/png');
assert.equal(manifest.icons[1].type, 'image/png');
assert.equal(manifest.icons[0].sizes, '192x192');
assert.equal(manifest.icons[1].sizes, '512x512');
assert.equal(manifest.shortcuts.length, 2);
assert.equal(manifest.shortcuts[0].url, './?view=inventory');
assert.equal(manifest.shortcuts[1].url, './?view=report');

const sw = await text('public/sw.js');
assert.match(sw, /caches\.open/);
assert.match(sw, /SKIP_WAITING/);
assert.match(sw, /cache: 'reload'/);
assert.match(sw, /no-store/);
assert.match(sw, /assetPathsFromHtml/);
assert.match(sw, /BUILD_ASSETS/);
assert.match(sw, /assets/);
assert.match(sw, /osteo3d-shell-v7/);
assert.match(sw, /osteo3d-192\.png/);
assert.match(sw, /osteo3d-512\.png/);
assert.match(sw, /models\/manifest\.json/);
assert.match(sw, /models\/sources\.json/);
assert.match(sw, /osteo3d-192\.svg/);
assert.match(sw, /osteo3d-512\.svg/);
assert.match(sw, /startsWith\('osteo3d-shell-'\)/);
assert.match(sw, /caches\.delete/);
assert.match(sw, /cache\.put\('\.\/index\.html', copy\)\)\.catch/);
assert.match(sw, /cache\.put\(event\.request, copy\)\)\.catch/);
assert.match(sw, /event\.request\.method !== 'GET'/);
assert.match(sw, /if \(!response\.ok\) throw/);
assert.match(sw, /if \(response\.ok\)/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /BUILD_ASSETS/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /fingerprintFiles/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /file !== 'sw\.js'/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /createHash/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /cacheFingerprint/);
assert.match(await text('scripts/check-js-syntax.mjs'), /JavaScript syntax OK/);
assert.match(await text('scripts/validate-pwa.mjs'), /fingerprint del build/);
assert.match(packageJson.scripts.build, /generate-sw-assets\.mjs/);

const main = await text('src/main.js');
const styles = await text('src/styles.css');
assert.match(main, /function renderViewerFallback\(error\)/);
assert.match(main, /WebGL is not available in this browser/);
assert.match(main, /regionLabel\(region\)/);
assert.match(main, /values\?\.\[7\].*textContent=source==='custom'/);
assert.match(main, /function profileLabel\(profileId\)/);
assert.match(main, /function localizePwaDiagnostics\(\)/);
assert.match(main, /function localizeModelPackagePanel\(\)/);
assert.match(main, /function reconcileVersionedShellDiagnostic\(\)/);
assert.match(main, /filter\(name=>name\.startsWith\('osteo3d-shell-'\)\)/);
assert.match(main, /setInterval\(reconcileVersionedShellDiagnostic,1000\)/);
assert.match(main, /if\(registration\.waiting\) registration\.waiting\.postMessage/);
assert.match(main, /else await registration\.update\(\)/);
assert.match(main, /document\.title=english\?'Osteo3D · Osteology atlas'/);
assert.match(main, /list\.innerHTML=checks\.join\('\'\); localizePwaDiagnostics\(\)/);
assert.match(main, /isSmallOrGrouped = \['Manos', 'Pies', 'Columna'\]/);
assert.match(main, /rib\|costilla\|c\(\?:1_atlas/);
assert.match(main, /data-fallback-bone/);
assert.match(main, /orbit\.target \|\|= \{ set\(\) \{\} \}/);
assert.match(styles, /\.viewer-fallback/);
const store = await text('src/data/store.js');
const translations = await text('src/i18n/translations.js');
const extendedUi = await text('src/ui/extended.js');
assert.match(store, /indexedDB/);
assert.match(store, /PROJECT_SCHEMA_VERSION = 2/);
assert.match(store, /normalizeProject/);
assert.match(store, /localStorage\.getItem/);
assert.match(store, /readFallbackProjects\(\)\.filter\(project => project\.id === id\)/);
assert.match(store, /newestProjects\(\[\.\.\.projects, \.\.\.readFallbackProjects\(\)\]\)/);
assert.match(main, /visualState=\{ hidden:state\.hidden/);
assert.match(main, /xray:state\.xray/);
assert.match(main, /labelMode:state\.labelMode/);
assert.match(main, /#profile.*saveLocal\(\{ notify: false \}\)/);
assert.doesNotMatch(main, /saved\?\.ue/);
const normalizedLegacy = normalizeProject({ profile: 'unknown', language: 'fr', report: null, filters: null });
assert.equal(normalizedLegacy.profile, 'adult_male');
assert.equal(normalizedLegacy.language, 'es');
assert.equal(normalizedLegacy.report.individual, 'IND-LOCAL');
assert.equal(normalizedLegacy.report.sources, '');
assert.equal(normalizedLegacy.report.method, '');
assert.equal(normalizedLegacy.report.limits, '');
const normalizedReport = normalizeProject({ report: { sources: 'DOI: test', method: 'Comparación', limits: 'Revisión pendiente' } });
assert.equal(normalizedReport.report.sources, 'DOI: test');
assert.equal(normalizedReport.report.method, 'Comparación');
assert.equal(normalizedReport.report.limits, 'Revisión pendiente');
const normalizedViewer = normalizeProject({ skeletonFilter: 'axial', regionFilter: 'Cráneo', explosion: 140, tableMode: 1, orthographic: 1, isolate: 1, explosionAnimating: 1 });
assert.equal(normalizedViewer.skeletonFilter, 'axial');
assert.equal(normalizedViewer.regionFilter, 'Cráneo');
assert.equal(normalizedViewer.explosion, 100);
assert.equal(normalizedViewer.tableMode, true);
assert.equal(normalizedViewer.explosionAnimating, false);
const normalizedDental = normalizeProject({ dental: { '11': 'fragmented', '12': 'invented' }, deciduousDental: ['invalid'], dentitionType: 'unknown' });
assert.equal(normalizedDental.dental['11'], 'fragmented');
assert.equal(normalizedDental.dental['12'], undefined);
assert.deepEqual(normalizedDental.deciduousDental, {});
assert.equal(normalizedDental.dentitionType, 'permanent');
const normalizedRecords = normalizeProject({ status: { skull: 'present', bad: 'unknown' }, preservation: { skull: 'good', bad: 'unknown' }, completeness: { skull: 140, bad: 'nan' }, fragments: { skull: 2.8 }, weights: { skull: -4, mandible: '12.5' }, individuals: { skull: ' IND-1 ' }, notes: { skull: ' Nota ' } });
assert.deepEqual(normalizedRecords.status, { skull: 'present' });
assert.deepEqual(normalizedRecords.preservation, { skull: 'good' });
assert.equal(normalizedRecords.completeness.skull, 100);
assert.equal(normalizedRecords.fragments.skull, 2);
assert.equal(normalizedRecords.weights.mandible, 12.5);
assert.equal(normalizedRecords.weights.skull, undefined);
assert.equal(normalizedRecords.individuals.skull, 'IND-1');
const normalizedFilters = normalizeProject({ filters: { status: 'invalid', region: 'invalid', side: 'left', taphonomy: 'invalid', preservation: 'invalid', type: 42 } });
assert.equal(normalizedFilters.filters.status, 'all');
assert.equal(normalizedFilters.filters.region, 'all');
assert.equal(normalizedFilters.filters.side, 'left');
assert.equal(normalizedFilters.filters.taphonomy, 'all');
assert.equal(normalizedFilters.filters.preservation, 'all');
assert.equal(normalizedFilters.filters.type, 'all');
const normalizedPhotos = normalizeProject({ photos: { skull: [{ name: 'ok', dataUrl: 'data:image/png;base64,AAAA', width: 10, height: 8 }, { name: 'bad', dataUrl: 'javascript:alert(1)' }] } });
assert.equal(normalizedPhotos.photos.skull.length, 1);
assert.equal(normalizedPhotos.photos.skull[0].dataUrl, 'data:image/png;base64,AAAA');
assert.match(styles, /:root\{/);
assert.match(styles, /\.layout\{/);
assert.match(styles, /canvas\{touch-action:none\}/);
assert.match(await text('src/pwa.css'), /safe-area-inset-top/);
assert.match(await text('src/pwa.css'), /safe-area-inset-bottom/);
assert.match(await text('src/pwa.css'), /@media\(max-width:650px\).*top-actions label\{display:inline-flex/s);
assert.match(await text('src/pwa.css'), /top-actions label select.*font-size:11px/s);
assert.match(store, /listProjects/);
assert.match(store, /projectName/);
for (const marker of ['inventory', 'dental', 'metrics', 'stats', 'report', 'scientificRecord', 'changes', 'sources']) assert.match(translations, new RegExp(`${marker}:`));
for (const marker of ['newProject', 'removePackage', 'refreshPwa', 'saveMetrics', 'printReport', 'installPwa', 'newVersion', 'updateNow']) assert.match(translations, new RegExp(`${marker}:`));
assert.match(translations, /share:/);
assert.match(main, /setInterval\(\(\) =>/);
assert.match(main, /connection-status/);
assert.match(main, /id="toast" role="status" aria-live="polite"/);
assert.match(main, /id="connection-status" class="connection-status" aria-live="polite"/);
assert.match(main, /id="storage-status" class="storage-status" aria-live="polite"/);
assert.match(main, /setTimeout\(\(\)=>\{URL\.revokeObjectURL\(a\.href\);a\.remove\(\);\},1000\)/);
assert.match(main, /filter-taphonomy/);
assert.match(main, /filter-pathology/);
assert.match(main, /conservation-map/);
assert.match(main, /function updateConservationMap/);
assert.match(main, /fragmentation-map/);
assert.match(main, /function updateFragmentationMap/);
assert.match(main, /frag\.\/elemento/);
assert.match(main, /function updateSideStats/);
assert.match(main, /side-stats/);
assert.match(main, /Representación por lateralidad/);
assert.match(main, /function updateQuantificationSummary/);
assert.match(main, /function skeletonMapReportHtml/);
assert.match(main, /Mapa esquelético esquemático/);
assert.match(main, /@page\{size:A4;margin:12mm\}/);
assert.match(main, /thead\{display:table-header-group\}/);
assert.match(main, /async function saveReportData/);
assert.match(main, /async function printReport\(\) \{ await saveReportData\(\)/);
assert.match(main, /function trapDialogFocus/);
assert.match(main, /previous\?\.isConnected/);
assert.match(main, /aria-describedby="project-name-description"/);
assert.match(main, /aria-describedby="confirm-action-description"/);
assert.match(main, /if\(document\.visibilityState==='visible'\)syncInventoryVisualColors\(\)/);
assert.match(main, /if\(document\.visibilityState==='visible'\)renderLabels\(\)/);
assert.match(main, /quantification-summary/);
assert.match(main, /analysis\.nisp\.value/);
assert.match(main, /analysis\.mne\.value/);
assert.match(main, /analysis\.mni\.value/);
assert.match(main, /function updateWeightSummary/);
assert.match(main, /Peso indeterminado/);
assert.match(main, /weight-summary/);
assert.match(main, /deciduousTeeth/);
assert.match(main, /dentition-type/);
assert.match(main, /Odontograma deciduo/);
assert.equal(manifest.scope, './');
for (const marker of ['PINTAR INVENTARIO', 'ODONTOGRAMA', 'OSTEOMETRÍA', 'ESTADÍSTICAS', 'INFORME OSTEOARQUEOLÓGICO', 'exportXlsx', 'registerPwa']) {
  assert.match(main, new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `Falta módulo: ${marker}`);
}
assert.match(main, /project-selector/);
assert.match(main, /extendedUi\?\.updateLabels\(\)/);
assert.match(main, /new-project/);
assert.match(main, /verifyModelPackages/);
assert.match(main, /protectLocalStorage/);
assert.match(main, /navigator\.storage\.persist/);
assert.match(main, /storage-status/);
assert.match(main, /pwa-diagnostics/);
assert.match(main, /inspector-toggle/);
assert.match(main, /mobile-open/);
assert.match(main, /runPwaDiagnostics/);
assert.match(main, /tableTransforms: \{\}/);
assert.match(main, /filters: \{ status: 'all', region: 'all', side: 'all', taphonomy: 'all', pathology: 'all', preservation: 'all', type: 'all' \}/);
assert.match(main, /indeterminateFragments: \[\]/);
assert.match(main, /beforeinstallprompt/);
assert.match(main, /appinstalled/);
assert.match(main, /PWA update deferred/);
assert.match(main, /event\.filename.*location\.origin/);
assert.match(main, /Añadir a pantalla de inicio/);
assert.match(main, /disponible en este navegador/);
assert.match(main, /cacheNames.*startsWith\('osteo3d-shell-v'\)/);
assert.doesNotMatch(main, /cacheName.*\|\|'osteo3d-shell-v7'/);
assert.match(main, /Iconos PWA/);
assert.match(main, /HTML, datos e iconos en caché/);
assert.match(main, /models\/sources\.json/);
assert.match(main, /applyPwaLaunchView/);
assert.match(main, /const activeId = localStorage\.getItem\('osteo3d-active-project'\) \|\| state\.projectId/);
assert.match(main, /applyProjectData\(savedProject\)/);
assert.match(main, /extendedUi\?\.updateLabels\(\);\s*populateReportFields\(\);/);
assert.doesNotMatch(main, /loadProject\('default'\)\.then\(saved=>\{/);
assert.doesNotMatch(main, /setTimeout\(async \(\) => \{ const savedProject = await loadProject\(state\.projectId\)/);
assert.doesNotMatch(main, /setTimeout\(async \(\) => \{ const saved = await loadProject\(state\.projectId\)/);
assert.doesNotMatch(main, /addEventListener\('click', \(\) => \{ state\.ue = \{\}; \}\)/);
assert.match(main, /function requestProjectName\(\)/);
assert.match(main, /aria-modal="true"/);
assert.doesNotMatch(main, /window\.prompt\(/);
assert.match(main, /function requestConfirmation\(message\)/);
assert.doesNotMatch(main, /window\.confirm\(/);
assert.match(main, /inventory-progress-label/);
assert.match(main, /Presencia rápida/);
assert.match(main, /Fragmentación rápida/);
assert.match(main, /multi-select-toggle/);
assert.match(main, /multi_select/);
assert.match(main, /multi-selected/);
assert.match(main, /aria-pressed="\$\{Boolean\(state\.multiSelected/);
assert.match(main, /aria-label="\$\{displayBoneName\(b\)\}/);
assert.match(main, /Marcar restantes como ausentes/);
assert.match(main, /requestConfirmation\(`Se marcarán/);
assert.match(main, /status-legend/);
assert.match(main, /Inventario completado/);
assert.match(main, /recordInventoryChange/);
assert.match(main, /recordInventoryFieldChange/);
assert.match(main, /field, previousValue, newValue/);
assert.match(main, /function focusSelectedBone/);
assert.match(main, /orbit\.radius = 8/);
assert.match(main, /function normalizeSearchText\(value\)/);
assert.match(main, /normalize\('NFD'\)/);
assert.match(main, /searchableBoneTerms\(b\)\.some\(v => v\.includes\(q\)\)/);
assert.match(main, /id="search-status" class="search-status small-copy" aria-live="polite"/);
assert.match(main, /searchStatus\.textContent = state\.language === 'en'/);
assert.match(main, /change', \(\) => \{ renderDental\(\); updateDentalCount\(\); renderList\(\); selectBone\(state\.selected\); \}\)/);
assert.match(main, /const matching=bones\.filter\(b=>matchesSkeletonFilter\(b\)&&matchesRegionFilter\(b\)/);
assert.match(main, /const exact=matching\.find/);
assert.match(main, /target=exact\|\|\(matching\.length===1\?matching\[0\]:null\)/);
assert.match(main, /if\(target&&target\.id!==state\.selected\)selectBone\(target\.id\)/);
assert.match(main, /commitInventoryEdit\('dental'/);
assert.match(main, /'measurements'/);
assert.match(main, /\['length', 'width', 'height', 'diameter'\]/);
assert.match(main, /unit: document\.querySelector\('#metric-unit'\)\?\.value === 'cm' \? 'cm' : 'mm'/);
assert.match(main, /'landmarks'/);
assert.match(main, /const visible=bones\.filter\(matchesFilters\)/);
assert.match(main, /class="bone-region-group" open/);
assert.match(main, /const regions = \[\.\.\.new Set\(groupBones\.map\(b => b\.region\)\)\]/);
assert.match(main, /function regionLabel\(region\)/);
assert.match(main, /regionLabel\(b\.region\)/);
assert.match(main, /function profileLabel\(profileId\)/);
assert.match(main, /Adult male/);
assert.match(main, /function inventoryColor\(status\)/);
assert.match(main, /function syncInventoryVisualColors\(\)/);
assert.match(main, /inventory-status-legend/);
assert.match(await text('src/pwa.css'), /status-swatch/);
assert.match(main, /function localizeStaticUi\(\)/);
assert.match(main, /document\.documentElement\.lang=state\.language/);
assert.match(main, /tableAdjust:'Table adjustment'/);
assert.match(main, /set\('#projection-toggle',state\.orthographic/);
assert.match(main, /data-lighting-mode/);
assert.match(main, /reportHtmlSource/);
assert.match(main, /html=html\.replace\('<html lang="es">','<html lang="en">'\)/);
assert.match(main, /Osteoarchaeological report/);
assert.match(main, /Permanent odontogram/);
assert.match(main, /Quantitative analysis/);
assert.match(main, /Taphonomy and pathology \/ trauma/);
assert.match(main, /\['Conservación media','Average completeness'\],\['Conservación','Preservation'\]/);
assert.match(main, /'Not evaluated'/);
assert.match(main, /No elements match the active filters/);
assert.match(main, /Individuals.*analysis\.individuals\.value/);
assert.match(main, /Downloading…/);
assert.match(main, /Offline GLB models for profile/);
assert.match(main, /Local GLB models imported/);
assert.match(main, /function localizePanelUi\(\)/);
assert.match(main, /Select a status and tap elements in the viewer/);
assert.match(main, /Save measurements/);
assert.match(main, /function localizeActiveStatusPrefix\(\)/);
assert.match(main, /function localizeDentalUi\(\)/);
assert.match(main, /Not observable/);
assert.match(main, /Dentition type/);
assert.match(main, /Fragmented/);
assert.match(main, /function localizePwaControls\(\)/);
assert.match(main, /Install PWA/);
assert.match(main, /Update now/);
assert.match(main, /Inspector/);
assert.match(main, /Drag to rotate · wheel to zoom/);
assert.match(main, /function localizeSecondaryControls\(\)/);
assert.match(main, /Orthographic projection/);
assert.match(main, /Hide bone/);
assert.match(main, /data-view-extra/);
assert.match(main, /const legendLabels=english\?\['Skull','Spine','Thorax','Extremities'\]/);
assert.match(main, /function localizeAccessibilityUi\(\)/);
assert.match(main, /Search bone, Latin name or ID/);
assert.match(main, /function localizeStatsUi\(\)/);
assert.match(main, /Clear filters/);
assert.match(main, /With record/);
assert.match(main, /function localizeReportUi\(\)/);
assert.match(main, /Generate report \/ print PDF/);
assert.match(main, /function localizeQuickInventoryUi\(\)/);
assert.match(main, /Quick presence:/);
assert.match(main, /Multi-selection:/);
assert.match(main, /function localizeReportExtendedUi\(\)/);
assert.match(main, /Associate photograph with/);
assert.match(main, /Interface error · local data preserved/);
assert.match(main, /Fallback atlas active · local data operational/);
assert.match(main, /function localizeModelPackageHelp\(\)/);
assert.match(main, /This profile has no licensed GLB models published yet/);
assert.match(main, /const sides=english\?\{'Izquierda':'Left','Derecha':'Right'\}/);
assert.match(main, /state\.isolate\?\(state\.language==='en'\?'Show skeleton':'Mostrar esqueleto'\)/);
assert.match(main, /state\.explosionAnimating\?\(state\.language==='en'\?'Pause deployment':'Pausar despliegue'\)/);
assert.match(main, /state\.wireframe\?\(english\?'Solid surface':'Superficie sólida'\)/);
assert.match(main, /state\.xray\?\(english\?'X-Ray enabled':'X-Ray activado'\)/);
assert.match(main, /state\.colorByRegion\?\(english\?'Colors by region':'Colores por región'\)/);
assert.match(main, /const categoryLabels=english\?\{craniometric:'Craniometric',osteometric:'Osteometric',pelvimetric:'Pelvimetric',dental:'Dental'\}/);
assert.match(main, /Elements with measurements:/);
assert.match(main, /Average completeness/);
assert.match(main, /Representation by laterality/);
assert.match(main, /OSTEOLOGY ATLAS/);
assert.match(main, /function refreshLocalizedStaticUi\(\)/);
assert.match(main, /Offline · local data/);
assert.match(main, /function refreshProfileDetailLabel\(\)/);
assert.match(await text('src/pwa.css'), /bone-region-group summary/);
assert.match(main, /filter-preservation/);
assert.match(main, /filter-type/);
assert.match(main, /filter\.preservation==='all'\|\|preservation===filter\.preservation/);
assert.match(main, /filter\.type==='all'\|\|bone\.type===filter\.type/);
assert.match(extendedUi, /formatChangeValue/);
assert.match(extendedUi, /entry\.field \?/);
assert.match(main, /'landmark_remove'/);
assert.match(main, /'lock'/);
assert.match(main, /state\.tableMode = false/);
assert.match(main, /state\.skeletonFilter = 'all'/);
assert.match(main, /state\.regionFilter = 'all'/);
assert.match(main, /state\.skeletonFilter = \['all', 'axial', 'appendicular'\]/);
assert.match(main, /state\.explosion = Math\.max\(0, Math\.min\(100/);
assert.match(main, /const tableModeButton = document\.querySelector\('#table-mode'\)/);
assert.match(main, /const projectionButton = document\.querySelector\('#projection-toggle'\)/);
assert.match(main, /camera = state\.orthographic \? new THREE\.OrthographicCamera/);
assert.match(main, /const wantedProjection = state\.orthographic/);
assert.match(main, /explosionAnimating: false/);
assert.match(main, /const explosionPlayButton = document\.querySelector\('#explosion-play'\)/);
assert.match(main, /runPwaDiagnostics\(\)\.catch\(\(\) => \{\}\)/);
assert.match(main, /commitInventoryEdit\('photo_remove'/);
assert.match(main, /commitInventoryEdit\('photo_add'/);
assert.match(main, /function safePhotoSource\(value\)/);
assert.match(main, /source:safePhotoSource\(photo\?\.dataUrl\)/);
assert.match(main, /data:image/);
assert.match(main, /recordInventorySnapshotChanges/);
assert.match(main, /'weights','weightUnits','portionRecords'/);
assert.match(main, /mass_absent/);
assert.match(main, /mass_region/);
assert.match(main, /'photos','indeterminateFragments','dental'/);
assert.match(main, /replaceChildren\(`0\/\$\{bones\.length\}`\)/);
assert.match(main, /replaceChildren\(`0\/\$\{bones\.length\} elementos revisados`\)/);
assert.match(main, /inspectorTabs\.setAttribute\('role', 'tablist'\)/);
assert.match(main, /aria-selected/);
assert.match(main, /MutationObserver\(syncInspectorTabA11y\)/);
assert.match(main, /ArrowLeft/);
assert.match(main, /tab\?\.focus\(\)/);
assert.match(main, /Buscar hueso, latín o identificador/);
assert.match(main, /Visor 3D del esqueleto/);
assert.match(main, /recordInventorySnapshotChanges\(current,previous,'undo'\)/);
assert.match(main, /data-paint-tool="preservation"/);
assert.match(main, /data-paint-tool="taphonomy"/);
assert.match(main, /data-paint-tool="erase"/);
assert.match(main, /state\.paintTool/);
assert.match(main, /paint-side-filter/);
assert.match(main, /Solo izquierda/);
assert.match(main, /matchesSide/);
assert.match(main, /changeLog/);
assert.match(main, /locked:state\.locked,changeLog:state\.changeLog/);
assert.match(main, /changeLog: \[\], quickPresent: false/);
assert.match(main, /\.\.\.createBackup\(state\),records:rows/);
assert.match(main, /visualState=\{ hidden:state\.hidden, opacity:state\.opacity, opacityScope:state\.opacityScope, wireframe:state\.wireframe/);
assert.match(main, /state\.labelMode = \['selected', 'region', 'all', 'none'\]\.includes\(saved\.labelMode\)/);
assert.match(main, /setComparisonProfile\(state\.comparisonProfile\)/);
assert.match(main, /await persistProject\(\{ \.\.\.data, \.\.\.visualState \}\)/);
assert.match(main, /state\.hidden = saved\.hidden/);
assert.match(main, /state\.tableTransforms = saved\.tableTransforms/);
assert.match(main, /Object\.assign\(state, saved, \{ projectId:/);
assert.match(extendedUi, /record-weight/);
assert.match(extendedUi, /Fragmentos indeterminados/);
assert.match(await text('src/data/store.js'), /indeterminateFragments/);
assert.match(await text('src/domain/backup.js'), /ue: \['UE', 'Context_UE'\]/);
assert.match(await text('src/domain/backup.js'), /report: state\.report/);
assert.match(await text('src/ui/extended.js'), /Registro de cambios/);
assert.match(await text('src/ui/extended.js'), /Fuentes y licencias/);
assert.match(await text('src/ui/extended.js'), /SOURCES\.md/);
assert.match(await text('src/ui/extended.js'), /changedAt/);
assert.match(main, /model-package-panel/);
assert.match(main, /downloadSelectedModelPackage/);
assert.match(main, /Se eliminarán los modelos GLB offline/);
assert.match(main, /Pendiente de incorporar assets licenciados/);
assert.match(main, /Descargar paquete offline/);
assert.match(main, /loadBoneModel/);
assert.match(main, /loadAvailableProfileModels/);
assert.match(main, /loadedModelObjects\.set\(bone\.id,model\); registerLandmarkModelReference\(bone\.id, modelSource\); if\(bone\.id===state\.selected\)refreshProfileDetailLabel\(\)/);
assert.match(main, /if \(modelManifest\) loadAvailableProfileModels\(\)/);
assert.match(main, /if \(group\) await loadAvailableProfileModels\(\)/);
assert.doesNotMatch(main, /setTimeout\(\(\) => \{ if \(modelManifest\) loadAvailableProfileModels/);
assert.match(main, /Mesa osteológica/);
assert.match(main, /tablePosition/);
assert.match(main, /state\.tableMode/);
assert.match(main, /tableTransforms/);
assert.match(main, /table-rotation/);
assert.match(main, /table-z/);
assert.match(main, /table-scale/);
assert.match(main, /baseScale/);
assert.match(main, /syncTableControls/);
assert.match(main, /skeleton-complete/);
assert.match(main, /skeletonFilter/);
assert.match(main, /matchesSkeletonFilter/);
assert.match(main, /bone-subgroup/);
assert.match(main, /Axial skeleton/);
assert.match(main, /function escapeHtml/);
assert.match(main, /escapeHtml\(photo\.name\)/);
assert.match(main, /region-filter-controls/);
assert.match(main, /matchesRegionFilter/);
assert.match(main, /data-region-filter="Cráneo"/);
assert.match(main, /setCameraProjection/);
assert.match(main, /OrthographicCamera/);
assert.match(main, /Proyección ortográfica/);
assert.match(main, /statusNamesEn/);
assert.match(main, /preservationNamesEn/);
assert.match(main, /very_fragmented/);
assert.match(main, /not_evaluable/);
assert.match(main, /function observationsReportHtml\(\)/);
assert.match(main, /Tafonomía y patología \/ trauma/);
assert.match(main, /taphonomyDetails:state\.taphonomyDetails/);
assert.match(main, /state\.taphonomyDetails = saved\.taphonomyDetails/);
assert.match(main, /taphonomyDetails: \{\}, pathologyDetails: \{\}, notes:/);
assert.match(main, /observationsReportHtml\(\)/);
assert.match(main, /Muy fragmentado/);
assert.match(main, /No evaluable/);
assert.match(main, /dentalNamesEn/);
assert.match(main, /displayBoneName/);
assert.match(main, /english\?'SELECTED':'SELECCIONADO'/);
assert.match(main, /hide-selected/);
assert.match(main, /state\.hidden\[id\]/);
assert.match(main, /opacity-slider/);
assert.match(main, /opacityForBone/);
assert.match(main, /opacityScope/);
assert.match(main, /Hueso seleccionado/);
assert.match(main, /Esqueleto completo/);
assert.match(main, /opacityScope/);
assert.match(main, /opacityForBone/);
assert.match(main, /Hueso seleccionado/);
assert.match(main, /Esqueleto completo/);
assert.match(main, /wireframe-toggle/);
assert.match(main, /xray-toggle/);
assert.match(main, /state\.xray/);
assert.match(main, /depthWrite=!state\.xray/);
assert.match(main, /labels-layer/);
assert.match(main, /renderLabels/);
assert.match(main, /labelMode/);
assert.match(main, /region-colors-toggle/);
assert.match(main, /colorByRegion/);
assert.match(main, /setComparisonProfile/);
assert.match(main, /comparisonGroup/);
assert.match(await text('src/ui/extended.js'), /compare-3d-toggle/);
assert.match(await text('src/ui/extended.js'), /oste3d:compare-profile/);
assert.match(main, /comparisonProfile/);
assert.match(main, /saveLocal\?\./);
assert.match(main, /explosion-play/);
assert.match(main, /explosionAnimating/);
assert.match(main, /reportRuntimeError/);
assert.match(main, /unhandledrejection/);
assert.match(main, /function hasExternalStack\(error\)/);
assert.match(main, /hasExternalStack\(event\.error\)/);
assert.match(main, /hasExternalStack\(event\.reason\)/);
assert.match(main, /appinstalled.*runPwaDiagnostics\(\)\.catch\(\(\)=>\{\}\)/s);
assert.match(main, /material\.wireframe=state\.wireframe/);
assert.match(main, /light-slider/);
assert.match(main, /setLightIntensity/);
assert.match(main, /scene\.userData\.lights/);
assert.match(store, /hidden: Object\.fromEntries/);
assert.match(store, /opacity: project\.opacity/);
assert.match(store, /opacityScope/);
assert.match(store, /opacityScope/);
assert.match(store, /wireframe: Boolean/);
assert.match(store, /lightIntensity/);
assert.match(store, /lightingMode/);
assert.match(main, /data-lighting-mode/);
assert.match(main, /function setLightingMode\(mode\)/);
assert.match(main, /lightingMode:state\.lightingMode/);
assert.match(main, /function setLightingDirection\(azimuth,elevation\)/);
assert.match(main, /ambientLightIntensity/);
assert.match(main, /lightingAzimuth/);
assert.match(main, /lightingElevation/);
assert.match(main, /id="ambient-slider"/);
assert.match(main, /id="opacity-slider" type="range" min="0" max="100"/);
assert.match(main, /data-local-view="medial"/);
assert.match(main, /data-local-view="proximal"/);
assert.match(main, /sources:'Fuentes consultadas'/);
assert.match(main, /method:'Método y alcance'/);
assert.match(main, /limits:'Limitaciones \/ revisión pendiente'/);
assert.match(main, /Sources:report.sources/);
assert.match(extendedUi, /commitInventoryEdit\('manual_analysis_review'/);
assert.match(await text('src/domain/inventory-history.js'), /'analysisReview'/);
assert.match(main, /setInspectorMobileOpen/);
assert.match(main, /event.key==='Escape'.*mobile-open/);
assert.match(await text('src/adaptive.css'), /min-height: 44px/);
assert.match(main, /Los datos científicos no se infieren a partir de la geometría/);
assert.match(main, /anatomy-facts/);
assert.match(main, /Anatomical landmarks/);
assert.match(main, /Anatomical reference/);
assert.match(main, /landmark-category/);
assert.match(main, /category: document\.querySelector\('#landmark-category'\)/);
assert.match(main, /data-view-extra="superior"/);
assert.match(main, /data-view-extra="inferior"/);
assert.match(main, /id="zoom-out"/);
assert.match(main, /id="zoom-in"/);
assert.match(main, /modelSource = 'glb'/);
assert.match(main, /intersectObjects\(group\.children\.filter\(object=>object\.visible\), true\)/);
assert.match(main, /listProjects, loadProject/);
assert.match(await text('src/ui/extended.js'), /compare-project/);
assert.match(await text('src/ui/extended.js'), /completeness:\s*numericRecord\(state\.completeness/);
assert.match(await text('src/ui/extended.js'), /taphonomy:\s*\(state\.taphonomy/);
assert.match(await text('src/ui/extended.js'), /patolog[ií]a\/trauma/);
assert.match(await text('src/ui/extended.js'), /diferencias frente a/);
assert.match(await text('src/ui/extended.js'), /comparisonIdentity/);
assert.match(await text('src/ui/extended.js'), /context: report\.context/);
assert.match(await text('src/ui/extended.js'), /portionRecords: portionSummary/);
assert.match(await text('src/ui/extended.js'), /Porciones independientes/);
assert.match(await text('src/ui/extended.js'), /individuo\/UE/);
assert.match(await text('src/ui/extended.js'), /compare-scope/);
assert.match(await text('src/ui/extended.js'), /comparisonScopeMatches/);
assert.match(await text('src/ui/extended.js'), /const numericRecord = \(records, id\)/);
assert.match(await text('src/ui/extended.js'), /Fragments: imported\.fragments\?\.\[boneId\] \?\? ''/);
assert.match(await text('src/ui/extended.js'), /populateComparisonScopes/);
assert.match(main, /Actualizar ahora/);
assert.match(main, /Más tarde/);
assert.match(main, /await saveLocal\(\{ notify:false \}\)/);
assert.match(main, /if\(updateRequested\) window\.location\.reload/);
assert.match(main, /onWheel/);
assert.match(main, /onPointerMove/);
assert.match(main, /orbit\.target/);
assert.match(main, /tabIndex = 0/);
assert.match(main, /aria-label.*Visor 3D/);
assert.match(main, /Árbol osteológico y estado PWA/);
assert.match(main, /Panel de inspección osteológica/);
assert.match(main, /id="update-actions"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(main, /#update-actions.*setAttribute\('aria-atomic', 'true'\)/);
assert.doesNotMatch(main, /setTimeout\(\(\) => \{ document\.querySelector\('\.top-actions'\)/);
assert.match(main, /onViewerKeyDown/);
assert.match(main, /ArrowLeft/);
assert.match(main, /toLowerCase\(\) === 'r'/);
assert.match(main, /data-row-status.*paintBone\(input\.dataset\.rowStatus\)/);
assert.match(main, /data-row-field="completeness".*recordInventoryFieldChange\(id, field, previous, next, 'table'\)/s);
assert.match(main, /boneId: 'Bone_ID'.*completeness: 'Completeness'.*notes: 'Observations'/s);
assert.match(main, /boneId: 'Bone_ID'.*completeness: 'Completitud'.*notes: 'Observaciones'/s);
assert.match(main, /inventory-table-scroll/);
assert.match(main, /data-row-field="preservation"/);
assert.match(main, /data-row-field="fragments"/);
assert.match(main, /data-row-field="taphonomy"/);
assert.match(main, /data-row-field="pathology"/);
assert.match(main, /data-row-field="notes"/);
assert.match(main, /paintBoneWithoutAudit\(id\).*saveLocal\(\{ notify: false \}\)/);
assert.match(main, /fragments:state\.fragments,weights:state\.weights,weightUnits:state\.weightUnits,portions/);
assert.match(main, /individuals:state\.individuals,ue:state\.ue/);
assert.match(main, /notes:state\.notes,indeterminateFragments:state\.indeterminateFragments/);
assert.match(main, /activePointers/);
assert.match(main, /pinchDistance/);
assert.match(main, /pointerDistance/);

assert.equal(await exists('src/anatomy/catalog.js'), true);
assert.equal(await exists('src/pwa-diagnostics.js'), true);
assert.match(main, /installCapabilityDiagnostics/);
assert.match(main, /IndexedDB disponible/);
assert.match(main, /respaldo localStorage disponible/);
assert.equal(await exists('src/anatomy/loader.js'), true);
assert.equal(await exists('src/anatomy/custom-loader.js'), true);
assert.match(await text('src/anatomy/custom-loader.js'), /OBJLoader/);
assert.match(await text('src/anatomy/custom-loader.js'), /STLLoader/);
assert.match(main, /Importar modelo propio/);
assert.match(main, /cacheCustomModelFile/);
assert.match(main, /loadCachedCustomModels/);
assert.match(main, /customModels:state\.customModels/);
assert.match(main, /loadedSource==='custom'\?\(english\?'Custom model':'Modelo propio'\)/);
assert.match(main, /Schematic 3D · uncalibrated/);
assert.match(main, /Categoría de inventario · sin malla/);
assert.match(main, /sidebarHeadings/);
assert.match(main, /function localizeTreeGroups().*COMPLETE SKELETON/);
assert.match(main, /const keys=\['complete','axial','appendicular'\]/);
assert.match(main, /function localizeInventoryActionLabels().*Show pending only/);
assert.match(main, /function localizeInteractionToast\(target\).*Complete skeleton/);
assert.match(main, /IndexedDB: disponible para proyectos locales/);
assert.match(main, /WebGL: visor 3D disponible/);
assert.match(main, /const english=state\.language==='en'; cacheElement\.textContent=`\$\{english\?'Offline cache'/);
assert.match(main, /setTimeout\(localizePwaDiagnostics,1500\)/);
assert.match(main, /const english=state\.language==='en'; const replacements=\[/);
assert.match(main, /const source=english\?from:to; const target=english\?to:from/);
assert.match(await text('src/i18n/translations.js'), /previous: 'Front'.*next: 'Back'/);
assert.match(main, /lowPowerDevice/);
assert.match(main, /powerPreference/);
assert.match(main, /renderer\.setPixelRatio\(lowPowerDevice \? 1/);
assert.match(main, /function yieldToBrowser\(\)/);
assert.match(main, /function forEachConcurrent\(items, concurrency, callback\)/);
assert.match(main, /const orderedBones = \[bones\.find\(bone => bone\.id === state\.selected\)/);
assert.match(main, /forEachConcurrent\(loadableBones, 8/);
assert.match(main, /dracoDecoderPath: '\.\/draco\/'/);
assert.match(await text('src/data/store.js'), /normalizeCustomModels/);
assert.match(await text('src/domain/backup.js'), /customModels: state\.customModels/);
assert.equal(await exists('src/anatomy/extended-bones.js'), true);
const { extendedBones } = await import('../src/anatomy/extended-bones.js');
assert.ok(extendedBones.length > 100, 'expanded catalog should contain independent placeholders');
assert.ok(extendedBones.some((bone) => bone.id === 'left_rib_1'));
assert.equal(extendedBones.find((bone) => bone.id === 'left_rib_1').en, 'Left rib 1');
assert.equal(extendedBones.find((bone) => bone.id === 'right_scapula').en, 'Right scapula');
assert.equal(extendedBones.find((bone) => bone.id === 'left_scaphoid').en, 'Left scaphoid');
for (const id of ['cervical_indeterminate', 'thoracic_indeterminate', 'lumbar_indeterminate', 'left_rib_indeterminate', 'right_rib_indeterminate', 'rib_indeterminate', 'carpal_indeterminate', 'metacarpal_indeterminate', 'hand_phalanx_indeterminate', 'tarsal_indeterminate', 'metatarsal_indeterminate', 'foot_phalanx_indeterminate']) assert.ok(extendedBones.some((bone) => bone.id === id), `missing catalog item ${id}`);
assert.equal(await exists('public/models/manifest.json'), true);
assert.match(await text('public/models/SOURCES.md'), /License\.txt/);
assert.match(await text('public/models/SOURCES.md'), /Open3Dmodel/);
assert.equal(await exists('public/draco/draco_decoder.js'), true);
assert.equal(await exists('public/draco/draco_decoder.wasm'), true);
assert.equal(await exists('public/draco/draco_wasm_wrapper.js'), true);
assert.equal(await exists('public/licenses/CC-BY-SA-4.0.txt'), true);
assert.equal(await exists('public/licenses/DRACO-APACHE-2.0.txt'), true);
assert.equal(await exists('public/icons/osteo3d-192.svg'), true);
assert.equal(await exists('public/icons/osteo3d-512.svg'), true);
assert.equal(await exists('public/icons/osteo3d-192.png'), true);
assert.equal(await exists('public/icons/osteo3d-512.png'), true);
const modelManifest = JSON.parse(await text('public/models/manifest.json'));
assert.equal(validateModelManifest(modelManifest, extendedBones).valid, true);
assert.equal(validateModelManifest({ ...modelManifest, bone_asset_pattern: '{profile}/model.glb' }, extendedBones).valid, false);
assert.equal(modelManifest.bone_count, 192);
assert.equal(modelManifest.profiles.adult_male.asset_count, 179);
const { buildOpen3dTargets } = await import('../scripts/extract-open3d-skeleton.mjs');
const open3dTargets = buildOpen3dTargets();
assert.equal(open3dTargets.length, 178);
assert.equal(new Set(open3dTargets.map(target => target.boneId)).size, 178);
assert.ok(open3dTargets.some(target => target.boneId === 'left_femur' && target.mirror));
assert.ok(open3dTargets.some(target => target.boneId === 'sternum' && target.sourceNames.length === 2));
assert.match(await text('src/anatomy/base-bones.js'), /left_coxal/);
assert.match(await text('src/anatomy/base-bones.js'), /right_coxal/);
assert.match(await text('src/anatomy/base-bones.js'), /region: 'Pelvis'/);
assert.match(main, /Columna cervical/);
assert.match(main, /Extremidad superior izquierda/);
assert.match(main, /matchesPaintRegion/);
assert.match(main, /detailHasValue/);
assert.match(main, /state\.taphonomyDetails\?\./);
assert.match(main, /state\.pathologyDetails\?\./);
assert.match(extendedUi, /TAPHONOMY_OPTIONS/);
assert.match(extendedUi, /record-taphonomy-type/);
assert.match(extendedUi, /taphonomyDetails\[id\]/);
assert.match(extendedUi, /PATHOLOGY_TYPES/);
assert.match(extendedUi, /record-pathology-description/);
assert.match(extendedUi, /pathologyDetails/);
assert.match(await text('src/domain/analysis.js'), /byContext/);
assert.match(await text('src/domain/analysis.js'), /byIndividual/);
assert.match(extendedUi, /NISP por contexto/);
assert.match(extendedUi, /indeterminate-quantity/);
assert.match(extendedUi, /indeterminate-thickness/);
assert.match(extendedUi, /quantity:/);
assert.match(main, /reportAnalysisSummaryHtml/);
assert.match(main, /Representación regional/);
assert.match(main, /Método MNE/);
assert.equal(modelPackageSummary(modelManifest, 'infant', extendedBones).status, 'partial');
assert.equal(modelPackageSummary(modelManifest, 'adult_male', extendedBones).availableCount, 179);
assert.equal(modelPackageSummary(modelManifest, 'adult_male', extendedBones).publishedCount, 179);
assert.equal(modelPackageSummary(modelManifest, 'infant', extendedBones).publishedCount, 179);
assert.equal(validateModelManifest({ ...modelManifest, profiles: { ...modelManifest.profiles, adult_male: { ...modelManifest.profiles.adult_male, asset_ids: [] } } }).valid, false);
assert.equal(formatPackageSize(null), 'no disponible');
assert.equal(formatPackageSize(42.5), 'aprox. 42.5 MB');
const sourceRegistry = JSON.parse(await text('public/models/sources.json'));
assert.equal(validateModelSourceRegistry(modelManifest, sourceRegistry).valid, true);
assert.equal(validateModelSourceRegistry({ profiles: { adult_female: { asset_status: 'ready' } } }, sourceRegistry).valid, true);
assert.equal(validateModelSourceRegistry(modelManifest, { ...sourceRegistry, schema_version: 99 }).valid, false);
assert.equal(validateModelSourceRegistry(modelManifest, { schema_version: 1, profiles: { adult_male: { source_status: 'pending' } } }).valid, false);
assert.match(await text('src/anatomy/loader.js'), /loadModelSourceRegistry/);
assert.equal(await exists('public/models/SOURCES.md'), true);
assert.match(await text('public/models/SOURCES.md'), /Anatria-3D/);
assert.equal(await exists('scripts/validate-model-assets.mjs'), true);
const packagePlan = modelPackageDownloadPlan(modelManifest, 'adult_male', [{ id: 'skull' }].map(bone => bone.id));
assert.equal(packagePlan.urls[0], './models/adult_male/skull.glb');
assert.deepEqual(modelPackageDownloadPlan(modelManifest, 'adult_male', ['skull', 'mandible']).urls, ['./models/adult_male/mandible.glb', './models/adult_male/skull.glb']);
assert.match(main, /Importar GLB locales/);
assert.match(main, /importLocalModelFiles/);
assert.match(main, /La importación reemplazará los modelos GLB locales/);
assert.match(await text('src/ui/extended.js'), /Vista previa de importación/);
assert.match(await text('src/ui/extended.js'), /function mergeAuxiliaryXlsx/);
assert.match(await text('src/ui/extended.js'), /Osteometría.*Landmarks.*Calibraciones/s);
assert.match(await text('src/ui/extended.js'), /#new-project.*newProject/);
assert.match(await text('src/ui/extended.js'), /\.pwa-update-label.*newVersion/);
assert.match(await text('src/ui/extended.js'), /Confirmar importación/);
assert.match(main, /const report=state\.report\|\|\{\}/);
assert.match(main, /Peso total registrado/);
assert.match(main, /Fragmentos indeterminados:/);
assert.match(main, /excluidos de NISP\/MNE\/MNI/);
assert.match(main, /dentalReportHtml/);
assert.match(main, /Odontograma permanente/);
assert.match(main, /calculateOsteoAnalysis/);
assert.match(main, /photosReportHtml/);
assert.match(main, /Taphonomy_Detail:JSON\.stringify/);
assert.match(main, /Pathology_Detail:JSON\.stringify/);
assert.match(main, /Taphonomy:\(state\.taphonomy\[b\.id\]\|\|\[\]\)\.join\('; '\)/);
assert.match(main, /Pathology:\(state\.pathology\[b\.id\]\|\|\[\]\)\.join\('; '\)/);
assert.match(main, /\.\.\.createBackup\(state\),records:rows/);
assert.match(main, /detailValues=\(details\)=>Object\.values\(details\|\|\{\}\)/);
assert.match(main, /takeInventorySnapshot\(state\)/);
assert.match(await text('src/domain/inventory-history.js'), /'taphonomyDetails', 'pathologyDetails'/);
assert.match(main, /delete state\.taphonomyDetails\[id\]/);
assert.match(main, /delete state\.pathologyDetails\[id\]/);
assert.match(main, /photo_add/);
assert.match(main, /photo_remove/);
assert.match(main, /state\.locked\[state\.selected\].*Registro bloqueado/);
assert.match(main, /importCustomModel = async file =>/);
assert.match(extendedUi, /indeterminate_fragment_add/);
assert.match(extendedUi, /indeterminate_fragment_remove/);
assert.match(extendedUi, /createOsteoArchive/);
assert.match(extendedUi, /readOsteoArchive/);
assert.match(await text('src/domain/backup-archive.js'), /sha256Hex/);
assert.match(await text('src/domain/backup-archive.js'), /version: 2/);
assert.match(extendedUi, /accept="\.osteo3d,\.json,\.csv,\.xlsx"/);
assert.match(extendedUi, /if \(hasTaphonomyDetail\) state\.taphonomyDetails\[id\] = taphonomyDetail; else delete state\.taphonomyDetails\[id\]/);
assert.match(extendedUi, /if \(hasPathologyDetail\) state\.pathologyDetails\[id\] = pathologyDetail; else delete state\.pathologyDetails\[id\]/);
assert.match(extendedUi, /Ficha contexto.*Fragmentos indeterminados.*Odontograma permanente.*Odontograma deciduo/s);
assert.match(extendedUi, /dental: importDentalRows\(value.dental/);
assert.match(extendedUi, /deciduousDental: importDentalRows\(value.deciduousDental/);
assert.match(main, /Método MNI/);
assert.match(main, /reviewed after filters/);
assert.match(main, /state\.filters\.preservation='all';state\.filters\.type='all'/);
assert.match(main, /average completeness recorded/);
assert.match(main, /const observed=items\.filter\(b=>state\.completeness\[b\.id\]!=null\)/);
assert.match(main, /const observed=identified\.filter\(bone=>state\.fragments\[bone\.id\]!=null/);
assert.match(main, /const observed=items\.filter\(bone=>state\.completeness\[bone\.id\]!=null&&Number\.isFinite/);
assert.match(main, /function syncSelectedCompletenessDisplay/);
assert.match(main, /const average=observed\.length\?Math\.round\(preserved\/observed\.length\):null/);
assert.match(main, /average == null \? '—' : `\$\{average\}%`/);
assert.match(main, /reportContextFields/);
assert.match(main, /const refreshDashboards=\(\)=>/);
assert.doesNotMatch(main, /setInterval\(update(?:ConservationMap|FragmentationMap|RegionalStats|SideStats|QuantificationSummary|WeightSummary),1000\)/);
assert.match(await text('scripts/verify-pages.mjs'), /Published Pages entry point/);
assert.match(await text('scripts/verify-pages.mjs'), /OSTEO3D_VERIFY_ATTEMPTS/);
assert.match(await text('scripts/verify-pages.mjs'), /OSTEO3D_VERIFY_DELAY_MS/);
assert.match(await text('.github/workflows/pages.yml'), /Verify published Pages entry point/);
assert.match(await text('index.html'), /Content-Security-Policy/);
assert.match(await text('index.html'), /connect-src 'self'/);
assert.match(await text('index.html'), /name="referrer" content="no-referrer"/);
assert.match(await text('scripts/validate-privacy.mjs'), /Privacy validation: no implicit external data transport/);
assert.match(await text('package.json'), /"validate-privacy": "node scripts\/validate-privacy\.mjs"/);
assert.match(main, /ensureLongReportFields/);
assert.match(main, /printableReportHtml/);
assert.match(main, /window\.open\('','_blank','noopener,noreferrer'\)/);
assert.match(main, /@page\{size:A4;margin:12mm\}/);
assert.match(main, /\['sources', 'method', 'limits'\]/);
assert.match(main, /translatedProvenanceReport/);
assert.match(main, /Sources consulted.*Method and scope.*Limitations \/ review pending/);
assert.match(main, /Ficha de contexto/);
assert.match(main, /Weight_g:state\.weights\[b\.id\]/);
assert.match(main, /indeterminateFragments:state\.indeterminateFragments/);
assert.match(main, /state\.indeterminateFragments = \[\]/);
assert.match(main, /Fragmentos indeterminados/);
assert.match(main, /escapeHtml\(individual\)/);
assert.match(main, /metric-diameter/);
assert.match(main, /metric-unit/);
assert.match(main, /Distancia entre landmarks/);
assert.match(main, /updateLandmarkVisuals/);
assert.match(main, /landmark-visuals/);
assert.match(main, /landmark-reference-mm/);
assert.match(main, /capture-surface-landmark/);
assert.match(main, /surface_pick/);
assert.match(main, /landmark_edit/);
assert.match(main, /data-save-landmark/);
assert.match(main, /landmark_calibration/);
assert.match(main, /landmarks:state\.landmarks,calibrations:state\.calibrations/);
assert.match(main, /landmarkModelRefs:state\.landmarkModelRefs/);
assert.match(main, /osteologySearchAliases/);
assert.match(main, /searchableBoneTerms/);
assert.match(main, /cubito: \['ulna'\].*ulna: \['cubito'\]/);
assert.match(main, /coxis: \['coccix', 'coccyx'\]/);
assert.match(main, /term\.startsWith\(`\$\{key\} `\)/);
assert.match(main, /portionRecords:state\.portionRecords/);
assert.match(main, /weightUnits:state\.weightUnits/);
assert.match(await text('src/ui/extended.js'), /record-weight-unit/);
assert.match(await text('src/ui/extended.js'), /indeterminate-weight-unit/);
assert.match(await text('src/domain/weights.js'), /weightToGrams/);
assert.match(main, /Independent portions/);
assert.match(main, /portion_records/);
assert.match(main, /save-portion-records/);
assert.match(main, /registerLandmarkModelReference/);
assert.match(main, /confirmLandmarkModelReference/);
assert.match(main, /confirm-landmark-model/);
assert.match(main, /needsReview/);
assert.match(main, /explosion-guides/);
assert.match(main, /guideLines/);
assert.match(main, /photo-scope/);
assert.match(main, /photoKey/);
assert.match(await text('src/domain/backup.js'), /photoScope/);
assert.match(main, /if \(scope && state\.photoScope\)/);
assert.match(main, /photoTargetId/);
assert.match(main, /photoScope:state\.photoScope/);
assert.match(main, /Selected element/);
assert.match(main, /FDI tooth/);
assert.match(main, /12\*1024\*1024/);
assert.match(main, /updateRegionalStats/);
assert.match(main, /regional-stats/);
assert.match(main, /async function exportXlsx/);
assert.match(main, /async function exportXlsx[\s\S]*Sources:report\.sources\|\|''[\s\S]*Method:report\.method\|\|''[\s\S]*Limits:report\.limits\|\|''/);
assert.match(main, /function appendAuxiliaryXlsxSheets/);
for (const sheetName of ['Osteometría', 'Landmarks', 'Calibraciones', 'Referencias landmarks', 'Revisión análisis', 'Registro de cambios', 'Fotografías', 'Modelos propios']) assert.match(main, new RegExp(`'${sheetName}'`));
assert.match(main, /sheet\('Esquema'/);
assert.match(main, /protectSpreadsheetRows/);
assert.match(await text('src/domain/spreadsheet.js'), /FORMULA_PREFIX/);
assert.match(styles, /:focus-visible/);
assert.match(styles, /prefers-reduced-motion/);
assert.match(main, /Locked:!!state\.locked\[b\.id\]/);
assert.match(main, /canvas\.toDataURL/);
assert.match(await text('src/ui/extended.js'), /quiz-level/);
assert.match(await text('src/ui/extended.js'), /close-learning/);
assert.match(await text('src/ui/extended.js'), /details.*hidden = true/);
assert.match(await text('src/ui/extended.js'), /optionCount/);
assert.match(await text('src/ui/extended.js'), /advanced/);
assert.match(await text('src/ui/extended.js'), /Identify bone/);
assert.match(await text('src/ui/extended.js'), /Locate bone/);
assert.match(await text('src/ui/extended.js'), /oste3d:bone-selected/);
assert.match(await text('src/ui/extended.js'), /Touch \$\{bone\.en\} in the 3D viewer/);
assert.match(await text('src/ui/extended.js'), /Correct answer/);
assert.match(main, /oste3d:bone-selected/);
assert.match(await text('src/anatomy/package.js'), /importModelPackageFiles/);
assert.match(await text('src/anatomy/loader.js'), /MeshoptDecoder/);
assert.match(await text('src/anatomy/loader.js'), /DRACOLoader/);
assert.match(await text('src/anatomy/custom-loader.js'), /setMeshoptDecoder/);
const modelCacheEntries = new Map();
globalThis.caches = { open: async () => ({ put: async (key, response) => modelCacheEntries.set(key, response), match: async key => modelCacheEntries.get(key) || undefined, delete: async key => modelCacheEntries.delete(key) }) };
const makeGlb = names => { const json = new TextEncoder().encode(JSON.stringify({ asset: { version: '2.0' }, nodes: names.map(name => ({ name })) })); const padded = new Uint8Array(Math.ceil(json.length / 4) * 4).fill(0x20); padded.set(json); const bytes = new Uint8Array(20 + padded.length); const view = new DataView(bytes.buffer); bytes.set([0x67, 0x6c, 0x54, 0x46], 0); view.setUint32(4, 2, true); view.setUint32(8, bytes.length, true); view.setUint32(12, padded.length, true); bytes.set([0x4a, 0x53, 0x4f, 0x4e], 16); bytes.set(padded, 20); return bytes.buffer; };
assert.equal(glbContainsBoneId(makeGlb(['skull']), 'skull'), true);
assert.equal(glbContainsBoneId(makeGlb(['other']), 'skull'), false);
const importedModels = await importModelPackageFiles('adult_male', [{ name: 'skull.glb', size: 64, arrayBuffer: async () => makeGlb(['skull']) }, { name: 'bad.glb', size: 64, arrayBuffer: async () => makeGlb(['other']) }, { name: 'notes.txt', size: 1, arrayBuffer: async () => new ArrayBuffer(1) }], ['skull', 'bad']);
assert.equal(importedModels.importedCount, 1);
assert.equal(importedModels.rejectedCount, 2);
assert.equal(modelCacheEntries.has('./models/adult_male/skull.glb'), true);
assert.deepEqual(await getCachedModelBoneIds('adult_male', ['skull', 'mandible']), ['skull']);
const customFile = { name: 'skull.glb', type: 'model/gltf-binary', size: 64, arrayBuffer: async () => makeGlb(['skull']) };
modelCacheEntries.set(customModelUrl('adult_male', 'skull', 'obj'), new Response('old'));
const customCache = await cacheCustomModelFile('adult_male', 'skull', customFile);
assert.equal(customCache.url, customModelUrl('adult_male', 'skull', 'glb'));
assert.equal((await globalThis.caches.open()).match(customCache.url) !== undefined, true);
assert.equal(modelCacheEntries.has(customModelUrl('adult_male', 'skull', 'obj')), false);
delete globalThis.caches;
await assert.rejects(() => downloadModelPackage(modelManifest, 'adult_male', ['skull']), /Cache Storage/);
assert.equal(await exists('dist/index.html'), true);
assert.equal(await exists('dist/sw.js'), true);
assert.equal(await exists('scripts/validate-pwa.mjs'), true);
assert.equal(await exists('scripts/e2e-pwa.mjs'), true);
assert.match(await text('README.md'), /Probar la PWA publicada/);
assert.match(await text('README.md'), /service worker activa el nuevo shell/);
assert.match(await text('scripts/validate-pwa.mjs'), /PWA artifact OK/);
assert.match(await text('scripts/validate-pwa.mjs'), /hasRequiredPngIcon/);
assert.match(await text('scripts/validate-pwa.mjs'), /SKIP_WAITING/);
assert.match(await text('scripts/validate-pwa.mjs'), /shortcutsValid/);
assert.match(await text('scripts/validate-pwa.mjs'), /index\\\.html/);
assert.match(await text('.github/workflows/pages.yml'), /pnpm validate-pwa/);
assert.match(await text('.github/workflows/pages.yml'), /pnpm test:e2e/);
assert.match(await text('package.json'), /"test:e2e": "node scripts\/e2e-pwa\.mjs"/);
assert.match(await text('scripts/e2e-pwa.mjs'), /emulateOfflineServiceWorker: offline/);
assert.match(await text('scripts/e2e-pwa.mjs'), /Network\.overrideNetworkState/);
assert.match(await text('scripts/e2e-pwa.mjs'), /server\.closeAllConnections/);
assert.equal(await exists('src/domain/analysis.js'), true);
assert.equal(await exists('src/domain/backup.js'), true);
assert.equal(await exists('src/ui/extended.js'), true);

const testBones = [
  { id: 'left_femur', es: 'Fémur izquierdo', region: 'Extremidad inferior', side: 'Izquierda' },
  { id: 'right_femur', es: 'Fémur derecho', region: 'Extremidad inferior', side: 'Derecha' }
];
const auxiliaryWorkbook = { Sheets: {
  'Osteometría': [{ Bone_ID: 'left_femur', length: 42.5, width: 11, unit: 'mm' }],
  'Landmarks': [{ Bone_ID: 'left_femur', name: 'Punto A', category: 'osteometric', x: 1, y: 2, z: 3 }],
  'Calibraciones': [{ Bone_ID: 'left_femur', referenceMm: 42.5, localDistance: 3.5 }],
  'Revisión análisis': [{ Metric: 'MNE', value: 2, reason: 'Revisión docente' }],
  'Registro de cambios': [{ Bone_ID: 'left_femur', Previous: '"present"', New: '"fragmentary"' }]
} };
const auxiliaryXlsx = mergeAuxiliaryXlsx({ measurements: {}, landmarks: {}, calibrations: {}, analysisReview: {}, changeLog: {} }, auxiliaryWorkbook, { utils: { sheet_to_json: sheet => sheet } }, testBones);
assert.equal(auxiliaryXlsx.measurements.left_femur.length, 42.5);
assert.equal(auxiliaryXlsx.landmarks.left_femur[0].name, 'Punto A');
assert.equal(auxiliaryXlsx.calibrations.left_femur.referenceMm, 42.5);
assert.equal(auxiliaryXlsx.analysisReview.mne.value, 2);
assert.equal(auxiliaryXlsx.changeLog[0].newValue, 'fragmentary');
const testState = { status: { left_femur: 'fragmentary', right_femur: 'not_recorded' }, fragments: { left_femur: 2 }, weights: { left_femur: 123.45 }, portions: { left_femur: 'epiphysis_proximal' }, individuals: { left_femur: 'IND-A' }, report: { individual: 'IND-TEST' } };
const analysis = calculateOsteoAnalysis(testBones, testState);
assert.equal(analysis.nisp.value, 1);
assert.equal(analysis.mne.value, 1);
assert.equal(analysis.mni.value, 1);
const mniWithIndividuals = calculateOsteoAnalysis(testBones, { status: { left_femur: 'present', right_femur: 'present' }, fragments: { left_femur: 4, right_femur: 4 }, individuals: { left_femur: 'IND-A', right_femur: 'IND-B' }, report: { individual: 'IND-LOCAL' } });
assert.equal(mniWithIndividuals.mni.value, 2);
const manyFragments=calculateOsteoAnalysis(testBones,{status:{left_femur:'fragmentary'},fragments:{left_femur:100},report:{individual:'IND-LOCAL'}});
assert.equal(manyFragments.mne.value,1);
assert.equal(manyFragments.mni.value,1);
const reviewedState={...testState,analysisReview:{mne:{value:2,reason:'Dos epífisis homólogas solapables; revisión de prueba',signature:JSON.stringify(analysis.rows)}}};
assert.equal(calculateOsteoAnalysis(testBones,reviewedState).mne.value,2);
assert.equal(calculateOsteoAnalysis(testBones,reviewedState).mne.provisional,false);
assert.equal(calculateOsteoAnalysis(testBones,{...reviewedState,fragments:{left_femur:3}}).mne.value,1);
assert.equal(calculateOsteoAnalysis(testBones,{status:{left_femur:'present'},report:{individual:'IND-LOCAL'}}).rows[0].fragments,null);
assert.equal(calculateOsteoAnalysis(testBones,{status:{left_femur:'present'},report:{individual:'IND-LOCAL'}}).rows[0].completeness,null);
assert.match(mniWithIndividuals.mni.method, /individuos explícitos/);
assert.equal(analysis.individuals.value, 1);
assert.equal(analysis.individuals.rows[0].individual, 'IND-A');
assert.equal(analysis.rows[0].weight, 123.45);
assert.ok(portionOptionsForBone({ type: 'long_bone' }).some(([key]) => key === 'epiphysis_proximal'));
assert.ok(!portionOptionsForBone({ type: 'rib' }).some(([key]) => key === 'epiphysis_proximal'));
assert.equal(parseCsv('Bone_ID,Presence\nleft_femur,present')[0].Bone_ID, 'left_femur');
const imported = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Presence: 'present', Individual_ID: 'IND-B', Weight_g: '88.2', Portion: 'shaft_mid', Taphonomy: 'raíces; erosión', Pathology: 'fractura', Burial: 'B-12', Grave: 'S-3', Tomb: 'T-2', UE: 'UE-4', Sector: 'Norte', Grid: 'A3', Site: 'Yacimiento X', Campaign: '2026', Date: '2026-09-08', Context: 'Osario', Chronology: 'siglo IV', Observations: 'Registro de prueba', Sources: 'DOI: prueba', Method: 'Comparación osteológica', Limits: 'Revisión pendiente' }], testBones);
assert.equal(imported.status.left_femur, 'present');
assert.equal(imported.rejectedRows, 0);
assert.equal(imported.individuals.left_femur, 'IND-B');
assert.equal(imported.report.sources, 'DOI: prueba');
assert.equal(imported.report.method, 'Comparación osteológica');
assert.equal(imported.report.limits, 'Revisión pendiente');
assert.equal(imported.portions.left_femur, 'shaft_mid');
assert.equal(imported.weights.left_femur, 88.2);
assert.deepEqual(imported.taphonomy.left_femur, ['raíces', 'erosión']);
assert.equal(imported.report.burial, 'B-12');
assert.equal(imported.report.individual, 'IND-B');
assert.equal(imported.report.ue, 'UE-4');
assert.equal(imported.report.chronology, 'siglo IV');
const rejectedRows = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Presence: 'present' }, { Bone_ID: 'left_femur', Presence: 'fragmentary' }, { Bone_ID: 'right_femur', Presence: 'invalid' }, { Bone_ID: 'unknown', Presence: 'present' }, { Bone_ID: 'left_tibia', Fragments: '1.5' }], testBones);
assert.equal(rejectedRows.importedRows, 1);
assert.equal(rejectedRows.rejectedRows, 4);
assert.equal(rejectedRows.validationErrors.length, 4);
assert.equal(rejectedRows.status.left_femur, 'present');
assert.equal(rejectedRows.status.right_femur, undefined);
assert.throws(() => parseCsv('Presence,Fragments\npresent,1'));
assert.throws(() => parseCsv('Bone_ID,Bone_ID\nleft_femur,left_femur'));
const structuredImported = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Taphonomy_Detail: JSON.stringify({ type: 'raíces', description: 'Galerías', position: 'diáfisis', extent: 'parcial', observations: 'Húmedo' }), Pathology_Detail: JSON.stringify({ type: 'fractura', description: 'Remodelada', position: 'epífisis', extent: 'localizada', observations: 'Antigua' }) }], testBones);
assert.equal(structuredImported.taphonomyDetails.left_femur.position, 'diáfisis');
assert.equal(structuredImported.pathologyDetails.left_femur.observations, 'Antigua');
const malformedDetails = applyInventoryRows({}, [{ Bone_ID: 'right_femur', Taphonomy_Detail: '{bad', Pathology_Detail: '[]' }], testBones);
assert.equal(malformedDetails.taphonomyDetails.right_femur, undefined);
assert.equal(malformedDetails.pathologyDetails.right_femur, undefined);
const sanitized = applyInventoryRows({}, [{ Bone_ID: ' right_femur ', Presence: 'unexpected', Percentage: 'nan', Fragments: '-2.8', Preservation: 'unexpected' }, { Bone_ID: 'unknown', Presence: 'present' }], testBones);
assert.equal(sanitized.status.right_femur, undefined);
assert.equal(sanitized.completeness.right_femur, undefined);
assert.equal(sanitized.fragments.right_femur, undefined);
assert.equal(sanitized.rejectedRows, 2);
const preservationTaxonomy = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Preservation: 'very_fragmented' }, { Bone_ID: 'right_femur', Preservation: 'not_evaluable' }], testBones);
assert.equal(preservationTaxonomy.preservation.left_femur, 'very_fragmented');
assert.equal(preservationTaxonomy.preservation.right_femur, 'not_evaluable');
assert.throws(() => validateBackup({ format: 'wrong' }));
const backup = createBackup({ projectId: 'field-01', projectName: 'Excavación 2026', schemaVersion: 2, profile: 'infant', selected: 'left_femur', status: {}, preservation: {}, completeness: {}, fragments: {}, weights: { left_femur: 88.2 }, portions: {}, individuals: {}, taphonomy: {}, pathology: {}, notes: {}, locked: {}, dental: {}, deciduousDental: { '51': 'present' }, dentitionType: 'deciduous', measurements: {}, landmarks: {}, photos: {}, language: 'en', filters: { status: 'present', region: 'all', side: 'left', taphonomy: 'all', pathology: 'all' }, report: {} });
assert.equal(validateBackup(backup).deciduousDental['51'], 'present');
assert.equal(validateBackup(backup).projectName, 'Excavación 2026');
assert.equal(validateBackup(backup).language, 'en');
assert.equal(validateBackup(backup).filters.side, 'left');
assert.equal(validateBackup(backup).weights.left_femur, 88.2);
assert.match(await text('src/ui/extended.js'), /if \(imported\.id\) state\.projectId = imported\.id/);
assert.match(await text('src/ui/extended.js'), /updateLabels\(\);\s+renderList/);
assert.deepEqual(validateBackup(createBackup({ ...backup.project, changeLog: [{ boneId: 'skull', previousStatus: 'not_recorded', newStatus: 'present' }] })).changeLog[0].newStatus, 'present');

console.log('Osteo3D smoke tests: OK');
