import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { access } from 'node:fs/promises';
import { calculateOsteoAnalysis } from '../src/domain/analysis.js';
import { portionOptionsForBone } from '../src/domain/portions.js';
import { downloadModelPackage, formatPackageSize, glbContainsBoneId, importModelPackageFiles, modelPackageDownloadPlan, modelPackageSummary, validateModelManifest, validateModelSourceRegistry } from '../src/anatomy/package.js';
import { applyInventoryRows, createBackup, parseCsv, validateBackup } from '../src/domain/backup.js';
import { normalizeProject } from '../src/data/store.js';

const text = async path => readFile(path, 'utf8');
const exists = async path => { try { await access(path); return true; } catch { return false; } };

const manifest = JSON.parse(await text('public/manifest.json'));
const packageJson = JSON.parse(await text('package.json'));
const indexHtml = await text('index.html');
assert.match(indexHtml, /apple-mobile-web-app-capable/);
assert.match(indexHtml, /apple-touch-icon.*osteo3d-192\.png/);
assert.equal(manifest.display, 'standalone');
assert.equal(packageJson.version, '1.0.0');
assert.equal(manifest.start_url, './');
assert.ok(manifest.icons.length > 0);
assert.equal(manifest.icons.length, 4);
assert.equal(manifest.icons[0].type, 'image/png');
assert.equal(manifest.icons[1].type, 'image/png');
assert.equal(manifest.icons[0].sizes, '192x192');
assert.equal(manifest.icons[1].sizes, '512x512');
assert.equal(manifest.shortcuts.length, 2);
assert.equal(manifest.shortcuts[0].url, './?view=inventory');
assert.equal(manifest.shortcuts[1].url, './?view=report');

const sw = await text('public/sw.js');
assert.match(sw, /caches\.open/);
assert.match(sw, /SKIP_WAITING/);
assert.match(sw, /cache: 'reload'/);
assert.match(sw, /no-store/);
assert.match(sw, /assetPathsFromHtml/);
assert.match(sw, /BUILD_ASSETS/);
assert.match(sw, /assets/);
assert.match(sw, /osteo3d-shell-v7/);
assert.match(sw, /osteo3d-192\.png/);
assert.match(sw, /osteo3d-512\.png/);
assert.match(sw, /models\/manifest\.json/);
assert.match(sw, /models\/sources\.json/);
assert.match(sw, /osteo3d-192\.svg/);
assert.match(sw, /osteo3d-512\.svg/);
assert.match(sw, /startsWith\('osteo3d-shell-'\)/);
assert.match(sw, /caches\.delete/);
assert.match(sw, /event\.request\.method !== 'GET'/);
assert.match(sw, /if \(!response\.ok\) throw/);
assert.match(sw, /if \(response\.ok\)/);
assert.match(await text('scripts/generate-sw-assets.mjs'), /BUILD_ASSETS/);
assert.match(packageJson.scripts.build, /generate-sw-assets\.mjs/);

const main = await text('src/main.js');
const styles = await text('src/styles.css');
const store = await text('src/data/store.js');
const translations = await text('src/i18n/translations.js');
const extendedUi = await text('src/ui/extended.js');
assert.match(store, /indexedDB/);
assert.match(store, /PROJECT_SCHEMA_VERSION = 2/);
assert.match(store, /normalizeProject/);
assert.match(store, /localStorage\.getItem/);
assert.match(store, /normalizeProject\(result\) \|\| readFallbackProject\(\)/);
assert.match(store, /projects\.length \? projects :/);
assert.match(main, /visualState=\{ hidden:state\.hidden/);
assert.match(main, /xray:state\.xray/);
assert.match(main, /labelMode:state\.labelMode/);
assert.match(main, /#profile.*saveLocal\(\{ notify: false \}\)/);
assert.doesNotMatch(main, /saved\?\.ue/);
const normalizedLegacy = normalizeProject({ profile: 'unknown', language: 'fr', report: null, filters: null });
assert.equal(normalizedLegacy.profile, 'adult_male');
assert.equal(normalizedLegacy.language, 'es');
assert.equal(normalizedLegacy.report.individual, 'IND-LOCAL');
const normalizedViewer = normalizeProject({ skeletonFilter: 'axial', regionFilter: 'Cráneo', explosion: 140, tableMode: 1, orthographic: 1, isolate: 1, explosionAnimating: 1 });
assert.equal(normalizedViewer.skeletonFilter, 'axial');
assert.equal(normalizedViewer.regionFilter, 'Cráneo');
assert.equal(normalizedViewer.explosion, 100);
assert.equal(normalizedViewer.tableMode, true);
assert.equal(normalizedViewer.explosionAnimating, false);
const normalizedDental = normalizeProject({ dental: { '11': 'fragmented', '12': 'invented' }, deciduousDental: ['invalid'], dentitionType: 'unknown' });
assert.equal(normalizedDental.dental['11'], 'fragmented');
assert.equal(normalizedDental.dental['12'], undefined);
assert.deepEqual(normalizedDental.deciduousDental, {});
assert.equal(normalizedDental.dentitionType, 'permanent');
const normalizedPhotos = normalizeProject({ photos: { skull: [{ name: 'ok', dataUrl: 'data:image/png;base64,AAAA', width: 10, height: 8 }, { name: 'bad', dataUrl: 'javascript:alert(1)' }] } });
assert.equal(normalizedPhotos.photos.skull.length, 1);
assert.equal(normalizedPhotos.photos.skull[0].dataUrl, 'data:image/png;base64,AAAA');
assert.match(styles, /:root\{/);
assert.match(styles, /\.layout\{/);
assert.match(styles, /canvas\{touch-action:none\}/);
assert.match(await text('src/pwa.css'), /safe-area-inset-top/);
assert.match(await text('src/pwa.css'), /safe-area-inset-bottom/);
assert.match(store, /listProjects/);
assert.match(store, /projectName/);
for (const marker of ['inventory', 'dental', 'metrics', 'stats', 'report', 'scientificRecord', 'changes', 'sources']) assert.match(translations, new RegExp(`${marker}:`));
for (const marker of ['newProject', 'removePackage', 'refreshPwa', 'saveMetrics', 'printReport', 'installPwa', 'newVersion', 'updateNow']) assert.match(translations, new RegExp(`${marker}:`));
assert.match(translations, /share:/);
assert.match(main, /setInterval\(\(\) =>/);
assert.match(main, /connection-status/);
assert.match(main, /id="toast" role="status" aria-live="polite"/);
assert.match(main, /setTimeout\(\(\)=>\{URL\.revokeObjectURL\(a\.href\);a\.remove\(\);\},1000\)/);
assert.match(main, /filter-taphonomy/);
assert.match(main, /filter-pathology/);
assert.match(main, /conservation-map/);
assert.match(main, /function updateConservationMap/);
assert.match(main, /fragmentation-map/);
assert.match(main, /function updateFragmentationMap/);
assert.match(main, /frag\.\/elemento/);
assert.match(main, /function updateSideStats/);
assert.match(main, /side-stats/);
assert.match(main, /Representación por lateralidad/);
assert.match(main, /function updateQuantificationSummary/);
assert.match(main, /quantification-summary/);
assert.match(main, /analysis\.nisp\.value/);
assert.match(main, /analysis\.mne\.value/);
assert.match(main, /analysis\.mni\.value/);
assert.match(main, /function updateWeightSummary/);
assert.match(main, /Peso indeterminado/);
assert.match(main, /weight-summary/);
assert.match(main, /deciduousTeeth/);
assert.match(main, /dentition-type/);
assert.match(main, /Odontograma deciduo/);
assert.equal(manifest.scope, './');
for (const marker of ['PINTAR INVENTARIO', 'ODONTOGRAMA', 'OSTEOMETRÍA', 'ESTADÍSTICAS', 'INFORME OSTEOARQUEOLÓGICO', 'exportXlsx', 'registerPwa']) {
  assert.match(main, new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `Falta módulo: ${marker}`);
}
assert.match(main, /project-selector/);
assert.match(main, /extendedUi\?\.updateLabels\(\)/);
assert.match(main, /new-project/);
assert.match(main, /verifyModelPackages/);
assert.match(main, /protectLocalStorage/);
assert.match(main, /navigator\.storage\.persist/);
assert.match(main, /storage-status/);
assert.match(main, /pwa-diagnostics/);
assert.match(main, /inspector-toggle/);
assert.match(main, /mobile-open/);
assert.match(main, /runPwaDiagnostics/);
assert.match(main, /tableTransforms: \{\}/);
assert.match(main, /filters: \{ status: 'all', region: 'all', side: 'all', taphonomy: 'all', pathology: 'all', preservation: 'all', type: 'all' \}/);
assert.match(main, /indeterminateFragments: \[\]/);
assert.match(main, /beforeinstallprompt/);
assert.match(main, /appinstalled/);
assert.match(main, /Añadir a pantalla de inicio/);
assert.match(main, /disponible en este navegador/);
assert.match(main, /osteo3d-shell-v7/);
assert.match(main, /Iconos PWA/);
assert.match(main, /HTML, datos e iconos en caché/);
assert.match(main, /models\/sources\.json/);
assert.match(main, /applyPwaLaunchView/);
assert.match(main, /const activeId = localStorage\.getItem\('osteo3d-active-project'\) \|\| state\.projectId/);
assert.match(main, /applyProjectData\(savedProject\)/);
assert.match(main, /extendedUi\?\.updateLabels\(\);\s*populateReportFields\(\);/);
assert.doesNotMatch(main, /loadProject\('default'\)\.then\(saved=>\{/);
assert.doesNotMatch(main, /setTimeout\(async \(\) => \{ const savedProject = await loadProject\(state\.projectId\)/);
assert.doesNotMatch(main, /setTimeout\(async \(\) => \{ const saved = await loadProject\(state\.projectId\)/);
assert.doesNotMatch(main, /addEventListener\('click', \(\) => \{ state\.ue = \{\}; \}\)/);
assert.match(main, /function requestProjectName\(\)/);
assert.match(main, /aria-modal="true"/);
assert.doesNotMatch(main, /window\.prompt\(/);
assert.match(main, /function requestConfirmation\(message\)/);
assert.doesNotMatch(main, /window\.confirm\(/);
assert.match(main, /inventory-progress-label/);
assert.match(main, /Presencia rápida/);
assert.match(main, /Fragmentación rápida/);
assert.match(main, /multi-select-toggle/);
assert.match(main, /multi_select/);
assert.match(main, /multi-selected/);
assert.match(main, /aria-pressed="\$\{Boolean\(state\.multiSelected/);
assert.match(main, /aria-label="\$\{displayBoneName\(b\)\}/);
assert.match(main, /Marcar restantes como ausentes/);
assert.match(main, /requestConfirmation\(`Se marcarán/);
assert.match(main, /status-legend/);
assert.match(main, /Inventario completado/);
assert.match(main, /recordInventoryChange/);
assert.match(main, /recordInventoryFieldChange/);
assert.match(main, /field, previousValue, newValue/);
assert.match(main, /function focusSelectedBone/);
assert.match(main, /orbit\.radius = 8/);
assert.match(main, /'dentalStatus'/);
assert.match(main, /'measurements'/);
assert.match(main, /const diameter=Number\(document\.querySelector\('#metric-diameter'\)\?\.value\)/);
assert.match(main, /unit:document\.querySelector\('#metric-unit'\)\?\.value==='cm'\?'cm':'mm'/);
assert.match(main, /'landmarks'/);
assert.match(main, /const visible=bones\.filter\(matchesFilters\)/);
assert.match(main, /filter-preservation/);
assert.match(main, /filter-type/);
assert.match(main, /filter\.preservation==='all'\|\|preservation===filter\.preservation/);
assert.match(main, /filter\.type==='all'\|\|bone\.type===filter\.type/);
assert.match(extendedUi, /formatChangeValue/);
assert.match(extendedUi, /entry\.field \?/);
assert.match(main, /'landmark_remove'/);
assert.match(main, /'lock'/);
assert.match(main, /state\.tableMode = false/);
assert.match(main, /state\.skeletonFilter = 'all'/);
assert.match(main, /state\.regionFilter = 'all'/);
assert.match(main, /state\.skeletonFilter = \['all', 'axial', 'appendicular'\]/);
assert.match(main, /state\.explosion = Math\.max\(0, Math\.min\(100/);
assert.match(main, /const tableModeButton = document\.querySelector\('#table-mode'\)/);
assert.match(main, /const projectionButton = document\.querySelector\('#projection-toggle'\)/);
assert.match(main, /camera = state\.orthographic \? new THREE\.OrthographicCamera/);
assert.match(main, /const wantedProjection = state\.orthographic/);
assert.match(main, /explosionAnimating: false/);
assert.match(main, /const explosionPlayButton = document\.querySelector\('#explosion-play'\)/);
assert.match(main, /runPwaDiagnostics\(\)\.catch\(\(\) => \{\}\)/);
assert.match(main, /recordInventoryFieldChange\(key,'photos',previous,photos,'photo_remove'\)/);
assert.match(main, /recordInventoryFieldChange\(key,'photos',previous,state\.photos\[key\],'photo_add'\)/);
assert.match(main, /function safePhotoSource\(value\)/);
assert.match(main, /source:safePhotoSource\(photo\?\.dataUrl\)/);
assert.match(main, /data:image/);
assert.match(main, /recordInventorySnapshotChanges/);
assert.match(main, /mass_absent/);
assert.match(main, /mass_region/);
assert.match(main, /replaceChildren\(`0\/\$\{bones\.length\}`\)/);
assert.match(main, /replaceChildren\(`0\/\$\{bones\.length\} elementos revisados`\)/);
assert.match(main, /inspectorTabs\.setAttribute\('role', 'tablist'\)/);
assert.match(main, /aria-selected/);
assert.match(main, /MutationObserver\(syncInspectorTabA11y\)/);
assert.match(main, /ArrowLeft/);
assert.match(main, /tab\?\.focus\(\)/);
assert.match(main, /Buscar hueso, latín o identificador/);
assert.match(main, /Visor 3D del esqueleto/);
assert.match(main, /recordInventorySnapshotChanges\(current,previous,'undo'\)/);
assert.match(main, /data-paint-tool="preservation"/);
assert.match(main, /data-paint-tool="taphonomy"/);
assert.match(main, /data-paint-tool="erase"/);
assert.match(main, /state\.paintTool/);
assert.match(main, /paint-side-filter/);
assert.match(main, /Solo izquierda/);
assert.match(main, /matchesSide/);
assert.match(main, /changeLog/);
assert.match(main, /locked:state\.locked,changeLog:state\.changeLog/);
assert.match(main, /changeLog: \[\], quickPresent: false/);
assert.match(main, /changeLog:state\.changeLog},null,2/);
assert.match(main, /visualState=\{ hidden:state\.hidden, opacity:state\.opacity, opacityScope:state\.opacityScope, wireframe:state\.wireframe/);
assert.match(main, /state\.labelMode = \['selected', 'region', 'all', 'none'\]\.includes\(saved\.labelMode\)/);
assert.match(main, /setComparisonProfile\(state\.comparisonProfile\)/);
assert.match(main, /localStorage\.setItem\('osteo3d-mvp'/);
assert.match(main, /state\.hidden = saved\.hidden/);
assert.match(main, /state\.tableTransforms = saved\.tableTransforms/);
assert.match(main, /Object\.assign\(state, saved, \{ projectId:/);
assert.match(extendedUi, /record-weight/);
assert.match(extendedUi, /Fragmentos indeterminados/);
assert.match(await text('src/data/store.js'), /indeterminateFragments/);
assert.match(await text('src/domain/backup.js'), /ue\[boneId\]/);
assert.match(await text('src/domain/backup.js'), /report: state\.report/);
assert.match(await text('src/ui/extended.js'), /Registro de cambios/);
assert.match(await text('src/ui/extended.js'), /Fuentes y licencias/);
assert.match(await text('src/ui/extended.js'), /SOURCES\.md/);
assert.match(await text('src/ui/extended.js'), /changedAt/);
assert.match(main, /model-package-panel/);
assert.match(main, /downloadSelectedModelPackage/);
assert.match(main, /Se eliminarán los modelos GLB offline/);
assert.match(main, /Pendiente de incorporar assets licenciados/);
assert.match(main, /Descargar paquete offline/);
assert.match(main, /loadBoneModel/);
assert.match(main, /loadAvailableProfileModels/);
assert.match(main, /Mesa osteológica/);
assert.match(main, /tablePosition/);
assert.match(main, /state\.tableMode/);
assert.match(main, /tableTransforms/);
assert.match(main, /table-rotation/);
assert.match(main, /table-z/);
assert.match(main, /table-scale/);
assert.match(main, /baseScale/);
assert.match(main, /syncTableControls/);
assert.match(main, /skeleton-complete/);
assert.match(main, /skeletonFilter/);
assert.match(main, /matchesSkeletonFilter/);
assert.match(main, /bone-subgroup/);
assert.match(main, /Axial skeleton/);
assert.match(main, /function escapeHtml/);
assert.match(main, /escapeHtml\(photo\.name\)/);
assert.match(main, /region-filter-controls/);
assert.match(main, /matchesRegionFilter/);
assert.match(main, /data-region-filter="Cráneo"/);
assert.match(main, /setCameraProjection/);
assert.match(main, /OrthographicCamera/);
assert.match(main, /Proyección ortográfica/);
assert.match(main, /statusNamesEn/);
assert.match(main, /preservationNamesEn/);
assert.match(main, /very_fragmented/);
assert.match(main, /not_evaluable/);
assert.match(main, /Muy fragmentado/);
assert.match(main, /No evaluable/);
assert.match(main, /dentalNamesEn/);
assert.match(main, /displayBoneName/);
assert.match(main, /english\?'SELECTED':'SELECCIONADO'/);
assert.match(main, /hide-selected/);
assert.match(main, /state\.hidden\[id\]/);
assert.match(main, /opacity-slider/);
assert.match(main, /opacityForBone/);
assert.match(main, /opacityScope/);
assert.match(main, /Hueso seleccionado/);
assert.match(main, /Esqueleto completo/);
assert.match(main, /opacityScope/);
assert.match(main, /opacityForBone/);
assert.match(main, /Hueso seleccionado/);
assert.match(main, /Esqueleto completo/);
assert.match(main, /wireframe-toggle/);
assert.match(main, /xray-toggle/);
assert.match(main, /state\.xray/);
assert.match(main, /depthWrite=!state\.xray/);
assert.match(main, /labels-layer/);
assert.match(main, /renderLabels/);
assert.match(main, /labelMode/);
assert.match(main, /region-colors-toggle/);
assert.match(main, /colorByRegion/);
assert.match(main, /setComparisonProfile/);
assert.match(main, /comparisonGroup/);
assert.match(await text('src/ui/extended.js'), /compare-3d-toggle/);
assert.match(await text('src/ui/extended.js'), /oste3d:compare-profile/);
assert.match(main, /comparisonProfile/);
assert.match(main, /saveLocal\?\./);
assert.match(main, /explosion-play/);
assert.match(main, /explosionAnimating/);
assert.match(main, /reportRuntimeError/);
assert.match(main, /unhandledrejection/);
assert.match(main, /material\.wireframe=state\.wireframe/);
assert.match(main, /light-slider/);
assert.match(main, /setLightIntensity/);
assert.match(main, /scene\.userData\.lights/);
assert.match(store, /hidden: project\.hidden/);
assert.match(store, /opacity: project\.opacity/);
assert.match(store, /opacityScope/);
assert.match(store, /opacityScope/);
assert.match(store, /wireframe: Boolean/);
assert.match(store, /lightIntensity/);
assert.match(store, /lightingMode/);
assert.match(main, /data-lighting-mode/);
assert.match(main, /function setLightingMode\(mode\)/);
assert.match(main, /lightingMode:state\.lightingMode/);
assert.match(main, /Los datos científicos no se infieren a partir de la geometría/);
assert.match(main, /anatomy-facts/);
assert.match(main, /Anatomical landmarks/);
assert.match(main, /Anatomical reference/);
assert.match(main, /landmark-category/);
assert.match(main, /category:document\.querySelector\('#landmark-category'\)/);
assert.match(main, /data-view-extra="superior"/);
assert.match(main, /data-view-extra="inferior"/);
assert.match(main, /id="zoom-out"/);
assert.match(main, /id="zoom-in"/);
assert.match(main, /modelSource: 'glb'/);
assert.match(main, /intersectObjects\(group\.children, true\)/);
assert.match(main, /listProjects, loadProject/);
assert.match(await text('src/ui/extended.js'), /compare-project/);
assert.match(await text('src/ui/extended.js'), /diferencias frente a/);
assert.match(main, /Actualizar ahora/);
assert.match(main, /Más tarde/);
assert.match(main, /await saveLocal\(\{ notify:false \}\)/);
assert.match(main, /if\(updateRequested\) window\.location\.reload/);
assert.match(main, /onWheel/);
assert.match(main, /onPointerMove/);
assert.match(main, /orbit\.target/);
assert.match(main, /tabIndex = 0/);
assert.match(main, /aria-label.*Visor 3D/);
assert.match(main, /Árbol osteológico y estado PWA/);
assert.match(main, /Panel de inspección osteológica/);
assert.match(main, /id="update-actions"[^>]*role="status"[^>]*aria-live="polite"/);
assert.match(main, /#update-actions.*setAttribute\('aria-atomic', 'true'\)/);
assert.doesNotMatch(main, /setTimeout\(\(\) => \{ document\.querySelector\('\.top-actions'\)/);
assert.match(main, /onViewerKeyDown/);
assert.match(main, /ArrowLeft/);
assert.match(main, /toLowerCase\(\) === 'r'/);
assert.match(main, /data-row-status.*paintBone\(input\.dataset\.rowStatus\)/);
assert.match(main, /data-row-field="completeness".*recordInventoryFieldChange\(id, field, previous, next, 'table'\)/s);
assert.match(main, /boneId: 'Bone_ID'.*completeness: 'Completeness'.*notes: 'Observations'/s);
assert.match(main, /boneId: 'Bone_ID'.*completeness: 'Completitud'.*notes: 'Observaciones'/s);
assert.match(main, /inventory-table-scroll/);
assert.match(main, /data-row-field="preservation"/);
assert.match(main, /data-row-field="fragments"/);
assert.match(main, /data-row-field="taphonomy"/);
assert.match(main, /data-row-field="pathology"/);
assert.match(main, /data-row-field="notes"/);
assert.match(main, /paintBoneWithoutAudit\(id\).*saveLocal\(\{ notify: false \}\)/);
assert.match(main, /fragments:state\.fragments,weights:state\.weights,portions/);
assert.match(main, /individuals:state\.individuals,ue:state\.ue/);
assert.match(main, /notes:state\.notes,indeterminateFragments:state\.indeterminateFragments/);
assert.match(main, /activePointers/);
assert.match(main, /pinchDistance/);
assert.match(main, /pointerDistance/);

assert.equal(await exists('src/anatomy/catalog.js'), true);
assert.equal(await exists('src/anatomy/loader.js'), true);
assert.equal(await exists('src/anatomy/custom-loader.js'), true);
assert.match(await text('src/anatomy/custom-loader.js'), /OBJLoader/);
assert.match(await text('src/anatomy/custom-loader.js'), /STLLoader/);
assert.match(main, /Importar modelo propio/);
assert.equal(await exists('src/anatomy/extended-bones.js'), true);
const { extendedBones } = await import('../src/anatomy/extended-bones.js');
assert.ok(extendedBones.length > 100, 'expanded catalog should contain independent placeholders');
assert.ok(extendedBones.some((bone) => bone.id === 'left_rib_1'));
for (const id of ['cervical_indeterminate', 'thoracic_indeterminate', 'lumbar_indeterminate', 'left_rib_indeterminate', 'right_rib_indeterminate', 'rib_indeterminate', 'carpal_indeterminate', 'metacarpal_indeterminate', 'hand_phalanx_indeterminate', 'tarsal_indeterminate', 'metatarsal_indeterminate', 'foot_phalanx_indeterminate']) assert.ok(extendedBones.some((bone) => bone.id === id), `missing catalog item ${id}`);
assert.equal(await exists('public/models/manifest.json'), true);
assert.match(await text('public/models/SOURCES.md'), /License\.txt/);
assert.equal(await exists('public/icons/osteo3d-192.svg'), true);
assert.equal(await exists('public/icons/osteo3d-512.svg'), true);
assert.equal(await exists('public/icons/osteo3d-192.png'), true);
assert.equal(await exists('public/icons/osteo3d-512.png'), true);
const modelManifest = JSON.parse(await text('public/models/manifest.json'));
assert.equal(validateModelManifest(modelManifest, extendedBones).valid, true);
assert.equal(validateModelManifest({ ...modelManifest, bone_asset_pattern: '{profile}/model.glb' }, extendedBones).valid, false);
assert.equal(modelManifest.bone_count, 192);
assert.match(main, /left_coxal/);
assert.match(main, /right_coxal/);
assert.match(main, /region: 'Pelvis'/);
assert.match(main, /Columna cervical/);
assert.match(main, /Extremidad superior izquierda/);
assert.match(main, /matchesPaintRegion/);
assert.equal(modelPackageSummary(modelManifest, 'infant', extendedBones).status, 'placeholder');
assert.equal(formatPackageSize(null), 'no disponible');
assert.equal(formatPackageSize(42.5), 'aprox. 42.5 MB');
const sourceRegistry = JSON.parse(await text('public/models/sources.json'));
assert.equal(validateModelSourceRegistry(modelManifest, sourceRegistry).valid, true);
assert.equal(validateModelSourceRegistry({ profiles: { adult_male: { asset_status: 'ready' } } }, sourceRegistry).valid, false);
assert.equal(validateModelSourceRegistry(modelManifest, { ...sourceRegistry, schema_version: 99 }).valid, false);
assert.equal(validateModelSourceRegistry(modelManifest, { schema_version: 1, profiles: { adult_male: { source_status: 'pending' } } }).valid, false);
assert.match(await text('src/anatomy/loader.js'), /loadModelSourceRegistry/);
assert.equal(await exists('public/models/SOURCES.md'), true);
assert.match(await text('public/models/SOURCES.md'), /Anatria-3D/);
assert.equal(await exists('scripts/validate-model-assets.mjs'), true);
const packagePlan = modelPackageDownloadPlan(modelManifest, 'adult_male', [{ id: 'skull' }].map(bone => bone.id));
assert.equal(packagePlan.urls[0], './models/adult_male/skull.glb');
assert.match(main, /Importar GLB locales/);
assert.match(main, /importLocalModelFiles/);
assert.match(main, /La importación reemplazará los modelos GLB locales/);
assert.match(await text('src/ui/extended.js'), /Vista previa de importación/);
assert.match(await text('src/ui/extended.js'), /#new-project.*newProject/);
assert.match(await text('src/ui/extended.js'), /\.pwa-update-label.*newVersion/);
assert.match(await text('src/ui/extended.js'), /Confirmar importación/);
assert.match(main, /const report=state\.report\|\|\{\}/);
assert.match(main, /Peso total registrado/);
assert.match(main, /Fragmentos indeterminados:/);
assert.match(main, /excluidos de NISP\/MNE\/MNI/);
assert.match(main, /dentalReportHtml/);
assert.match(main, /Odontograma permanente/);
assert.match(main, /calculateOsteoAnalysis/);
assert.match(main, /photosReportHtml/);
assert.match(main, /Método MNI/);
assert.match(main, /reviewed after filters/);
assert.match(main, /average completeness recorded/);
assert.match(main, /reportContextFields/);
assert.match(main, /Ficha de contexto/);
assert.match(main, /Weight_g:state\.weights\[b\.id\]/);
assert.match(main, /indeterminateFragments:state\.indeterminateFragments/);
assert.match(main, /state\.indeterminateFragments = \[\]/);
assert.match(main, /Fragmentos indeterminados/);
assert.match(main, /escapeHtml\(individual\)/);
assert.match(main, /metric-diameter/);
assert.match(main, /metric-unit/);
assert.match(main, /Distancia entre landmarks/);
assert.match(main, /updateLandmarkVisuals/);
assert.match(main, /landmark-visuals/);
assert.match(main, /explosion-guides/);
assert.match(main, /guideLines/);
assert.match(main, /photo-scope/);
assert.match(main, /photoKey/);
assert.match(await text('src/domain/backup.js'), /photoScope/);
assert.match(main, /if \(scope && state\.photoScope\)/);
assert.match(main, /photoTargetId/);
assert.match(main, /Selected element/);
assert.match(main, /FDI tooth/);
assert.match(main, /12\*1024\*1024/);
assert.match(main, /updateRegionalStats/);
assert.match(main, /regional-stats/);
assert.match(main, /async function exportXlsx/);
assert.match(main, /Locked:!!state\.locked\[b\.id\]/);
assert.match(main, /canvas\.toDataURL/);
assert.match(await text('src/ui/extended.js'), /quiz-level/);
assert.match(await text('src/ui/extended.js'), /optionCount/);
assert.match(await text('src/ui/extended.js'), /advanced/);
assert.match(await text('src/ui/extended.js'), /Identify bone/);
assert.match(await text('src/ui/extended.js'), /Correct answer/);
assert.match(await text('src/anatomy/package.js'), /importModelPackageFiles/);
assert.match(await text('src/anatomy/loader.js'), /MeshoptDecoder/);
assert.match(await text('src/anatomy/loader.js'), /DRACOLoader/);
assert.match(await text('src/anatomy/custom-loader.js'), /setMeshoptDecoder/);
const modelCacheEntries = new Map();
globalThis.caches = { open: async () => ({ put: async (key, response) => modelCacheEntries.set(key, response) }) };
const makeGlb = names => { const json = new TextEncoder().encode(JSON.stringify({ asset: { version: '2.0' }, nodes: names.map(name => ({ name })) })); const padded = new Uint8Array(Math.ceil(json.length / 4) * 4).fill(0x20); padded.set(json); const bytes = new Uint8Array(20 + padded.length); const view = new DataView(bytes.buffer); bytes.set([0x67, 0x6c, 0x54, 0x46], 0); view.setUint32(4, 2, true); view.setUint32(8, bytes.length, true); view.setUint32(12, padded.length, true); bytes.set([0x4a, 0x53, 0x4f, 0x4e], 16); bytes.set(padded, 20); return bytes.buffer; };
assert.equal(glbContainsBoneId(makeGlb(['skull']), 'skull'), true);
assert.equal(glbContainsBoneId(makeGlb(['other']), 'skull'), false);
const importedModels = await importModelPackageFiles('adult_male', [{ name: 'skull.glb', size: 64, arrayBuffer: async () => makeGlb(['skull']) }, { name: 'bad.glb', size: 64, arrayBuffer: async () => makeGlb(['other']) }, { name: 'notes.txt', size: 1, arrayBuffer: async () => new ArrayBuffer(1) }], ['skull', 'bad']);
assert.equal(importedModels.importedCount, 1);
assert.equal(importedModels.rejectedCount, 2);
assert.equal(modelCacheEntries.has('./models/adult_male/skull.glb'), true);
delete globalThis.caches;
await assert.rejects(() => downloadModelPackage(modelManifest, 'adult_male', ['skull']), /placeholder/);
assert.equal(await exists('dist/index.html'), true);
assert.equal(await exists('dist/sw.js'), true);
assert.equal(await exists('scripts/validate-pwa.mjs'), true);
assert.match(await text('scripts/validate-pwa.mjs'), /PWA artifact OK/);
assert.match(await text('scripts/validate-pwa.mjs'), /hasRequiredPngIcon/);
assert.match(await text('scripts/validate-pwa.mjs'), /SKIP_WAITING/);
assert.match(await text('.github/workflows/pages.yml'), /pnpm validate-pwa/);
assert.equal(await exists('src/domain/analysis.js'), true);
assert.equal(await exists('src/domain/backup.js'), true);
assert.equal(await exists('src/ui/extended.js'), true);

const testBones = [
  { id: 'left_femur', es: 'Fémur izquierdo', region: 'Extremidad inferior', side: 'Izquierda' },
  { id: 'right_femur', es: 'Fémur derecho', region: 'Extremidad inferior', side: 'Derecha' }
];
const testState = { status: { left_femur: 'fragmentary', right_femur: 'not_recorded' }, fragments: { left_femur: 2 }, weights: { left_femur: 123.45 }, portions: { left_femur: 'epiphysis_proximal' }, individuals: { left_femur: 'IND-A' }, report: { individual: 'IND-TEST' } };
const analysis = calculateOsteoAnalysis(testBones, testState);
assert.equal(analysis.nisp.value, 1);
assert.equal(analysis.mne.value, 2);
assert.equal(analysis.mni.value, 1);
const mniWithIndividuals = calculateOsteoAnalysis(testBones, { status: { left_femur: 'present', right_femur: 'present' }, fragments: { left_femur: 4, right_femur: 4 }, individuals: { left_femur: 'IND-A', right_femur: 'IND-B' }, report: { individual: 'IND-LOCAL' } });
assert.equal(mniWithIndividuals.mni.value, 1);
assert.match(mniWithIndividuals.mni.method, /individuos explícitos/);
assert.equal(analysis.individuals.value, 1);
assert.equal(analysis.individuals.rows[0].individual, 'IND-A');
assert.equal(analysis.rows[0].weight, 123.45);
assert.ok(portionOptionsForBone({ type: 'long_bone' }).some(([key]) => key === 'epiphysis_proximal'));
assert.ok(!portionOptionsForBone({ type: 'rib' }).some(([key]) => key === 'epiphysis_proximal'));
assert.equal(parseCsv('Bone_ID,Presence\nleft_femur,present')[0].Bone_ID, 'left_femur');
const imported = applyInventoryRows({}, [{ Bone_ID: 'left_femur', Presence: 'present', Individual_ID: 'IND-B', Weight_g: '88.2', Portion: 'shaft_mid', Taphonomy: 'raíces; erosión', Pathology: 'fractura', Burial: 'B-12', Grave: 'S-3', Tomb: 'T-2', UE: 'UE-4', Sector: 'Norte', Grid: 'A3', Site: 'Yacimiento X', Campaign: '2026', Date: '2026-09-08', Context: 'Osario', Chronology: 'siglo IV', Observations: 'Registro de prueba' }], testBones);
assert.equal(imported.status.left_femur, 'present');
assert.equal(imported.rejectedRows, 0);
assert.equal(imported.individuals.left_femur, 'IND-B');
assert.equal(imported.portions.left_femur, 'shaft_mid');
assert.equal(imported.weights.left_femur, 88.2);
assert.deepEqual(imported.taphonomy.left_femur, ['raíces', 'erosión']);
assert.equal(imported.report.burial, 'B-12');
assert.equal(imported.report.ue, 'UE-4');
assert.equal(imported.report.chronology, 'siglo IV');
const sanitized = applyInventoryRows({}, [{ Bone_ID: ' right_femur ', Presence: 'unexpected', Percentage: 'nan', Fragments: '-2.8', Preservation: 'unexpected' }, { Bone_ID: 'unknown', Presence: 'present' }], testBones);
assert.equal(sanitized.status.right_femur, 'not_recorded');
assert.equal(sanitized.completeness.right_femur, 100);
assert.equal(sanitized.fragments.right_femur, 0);
assert.equal(sanitized.rejectedRows, 1);
assert.throws(() => validateBackup({ format: 'wrong' }));
const backup = createBackup({ projectId: 'field-01', projectName: 'Excavación 2026', schemaVersion: 2, profile: 'infant', selected: 'left_femur', status: {}, preservation: {}, completeness: {}, fragments: {}, weights: { left_femur: 88.2 }, portions: {}, individuals: {}, taphonomy: {}, pathology: {}, notes: {}, locked: {}, dental: {}, deciduousDental: { '51': 'present' }, dentitionType: 'deciduous', measurements: {}, landmarks: {}, photos: {}, language: 'en', filters: { status: 'present', region: 'all', side: 'left', taphonomy: 'all', pathology: 'all' }, report: {} });
assert.equal(validateBackup(backup).deciduousDental['51'], 'present');
assert.equal(validateBackup(backup).projectName, 'Excavación 2026');
assert.equal(validateBackup(backup).language, 'en');
assert.equal(validateBackup(backup).filters.side, 'left');
assert.equal(validateBackup(backup).weights.left_femur, 88.2);
assert.match(await text('src/ui/extended.js'), /if \(imported\.id\) state\.projectId = imported\.id/);
assert.match(await text('src/ui/extended.js'), /updateLabels\(\);\s+renderList/);
assert.deepEqual(validateBackup(createBackup({ ...backup.project, changeLog: [{ boneId: 'skull', previousStatus: 'not_recorded', newStatus: 'present' }] })).changeLog[0].newStatus, 'present');

console.log('Osteo3D smoke tests: OK');
